import http from 'node:http';
import crypto from 'node:crypto';
import { WebSocketServer, WebSocket } from 'ws';
import { StatusWriter } from '../status/statusWriter';
import type { VPBridgeConfig } from '../config/config';
import { MessageQueue } from '../bridge/messageQueue';
import type { BridgeMessage, MessageDirection } from '../bridge/message';
import { Logger } from '../logging/logger';
const VERSION='0.6.5'; type Side='VP'|'BC';
export class VPBridgeServer {private readonly httpServer:http.Server;private readonly wsServer:WebSocketServer;private readonly vpToBcQueue:MessageQueue;private readonly bcToVpQueue:MessageQueue;private readonly statusWriter:StatusWriter;private vpClient?:WebSocket;private bcClient?:WebSocket;private nextMessageId=1;private flushingVpToBc=false;private flushingBcToVp=false;
constructor(private readonly config:VPBridgeConfig,private readonly logger:Logger){this.vpToBcQueue=new MessageQueue(config.queue.maxMessages);this.bcToVpQueue=new MessageQueue(config.queue.maxMessages);this.statusWriter=new StatusWriter({serverRunning:false,vpConnected:false,bcConnected:false,host:config.server.host,port:config.server.port});this.httpServer=http.createServer();this.wsServer=new WebSocketServer({noServer:true});this.httpServer.on('upgrade',(request,socket,head)=>{const url=new URL(request.url??'/',`http://${request.headers.host??'localhost'}`);const pathname=url.pathname;if(pathname!==config.server.vpPath&&pathname!==config.server.bcPath){socket.write('HTTP/1.1 404 Not Found\r\n\r\n');socket.destroy();return}if(config.server.mode==='all'){const suppliedKey=url.searchParams.get('apiKey')??'';if(!this.isApiKeyValid(suppliedKey)){this.logger.system(`AUTH REJECTED for ${pathname} from ${request.socket.remoteAddress??'unknown'}`);socket.write('HTTP/1.1 401 Unauthorized\r\nConnection: close\r\n\r\n');socket.destroy();return}}this.wsServer.handleUpgrade(request,socket,head,ws=>this.wsServer.emit('connection',ws,request,pathname))});this.wsServer.on('connection',(ws:WebSocket,_request:http.IncomingMessage,pathname:string)=>{if(pathname===config.server.vpPath)this.attachVp(ws);else if(pathname===config.server.bcPath)this.attachBc(ws)})}
start():Promise<void>{return new Promise((resolve,reject)=>{this.httpServer.once('error',reject);this.httpServer.listen(this.config.server.port,this.config.server.host,()=>{this.httpServer.off('error',reject);this.logger.system(`VPBridge v${VERSION} listening on ws://${this.config.server.host}:${this.config.server.port}`);this.logger.system(`VP endpoint: ${this.config.server.vpPath}`);this.logger.system(`BC endpoint: ${this.config.server.bcPath}`);this.logger.system('Bidirectional transport enabled: VP→BC and BC→VP');this.logger.system(`Listen mode: ${this.config.server.mode==='all'?'All Interfaces (API key required)':'Local only'}`);this.statusWriter.update({serverRunning:true,vpConnected:false,bcConnected:false,host:this.config.server.host,port:this.config.server.port});resolve()})})}
stop():Promise<void>{return new Promise(resolve=>{this.logger.system('Stopping VPBridge; clearing both RAM queues');this.vpToBcQueue.clear();this.bcToVpQueue.clear();this.vpClient?.close();this.bcClient?.close();this.wsServer.close();this.statusWriter.update({serverRunning:false,vpConnected:false,bcConnected:false});this.httpServer.close(()=>resolve())})}
private attachVp(ws:WebSocket):void{if(this.vpClient&&this.vpClient.readyState===WebSocket.OPEN){this.logger.system('New VP connection replaced previous VP connection');this.vpClient.close(4000,'Replaced by new VP connection')}this.vpClient=ws;this.logger.system('VP CONNECTED');this.statusWriter.update({vpConnected:true});ws.on('message',(data,isBinary)=>{if(isBinary){this.logger.system('VP binary message ignored');return}this.receiveMessage('VP_TO_BC',data.toString())});ws.on('close',()=>{if(this.vpClient!==ws){this.logger.system('VP DISCONNECTED (replaced connection)');return}this.vpClient=undefined;this.logger.system('VP DISCONNECTED');this.statusWriter.update({vpConnected:false});this.handleDestinationDisconnect('BC_TO_VP')});ws.on('error',err=>this.logger.system(`VP ERROR: ${err.message}`));void this.flushDirection('BC_TO_VP')}
private attachBc(ws:WebSocket):void{if(this.bcClient&&this.bcClient.readyState===WebSocket.OPEN){this.logger.system('New BC connection replaced previous BC connection');this.bcClient.close(4000,'Replaced by new BC connection')}this.bcClient=ws;this.logger.system('BC CONNECTED');this.statusWriter.update({bcConnected:true});ws.on('message',(data,isBinary)=>{if(isBinary){this.logger.system('BC binary message ignored');return}this.receiveMessage('BC_TO_VP',data.toString())});ws.on('close',()=>{if(this.bcClient!==ws){this.logger.system('BC DISCONNECTED (replaced connection)');return}this.bcClient=undefined;this.logger.system('BC DISCONNECTED');this.statusWriter.update({bcConnected:false});this.handleDestinationDisconnect('VP_TO_BC')});ws.on('error',err=>this.logger.system(`BC ERROR: ${err.message}`));void this.flushDirection('VP_TO_BC')}
private receiveMessage(direction:MessageDirection,payload:string):void{try{JSON.parse(payload)}catch{const invalidId=this.nextMessageId++;this.logger.message(invalidId,direction,'DROPPED',payload);this.logger.system(`#${invalidId} ${this.directionLabel(direction)} dropped: INVALID JSON`);return}const message:BridgeMessage={id:this.nextMessageId++,receivedAt:new Date(),direction,payload};this.logger.message(message.id,message.direction,'RECEIVED',payload);const destinationOnline=this.isDestinationOnline(direction);const queue=this.getQueue(direction);if(!destinationOnline){if(this.config.queue.offlineBufferSize===0){this.logger.message(message.id,message.direction,'DROPPED');this.logger.system(`#${message.id} ${this.directionLabel(direction)} dropped: ${this.destinationName(direction)} not connected and offline buffer disabled`);return}message.bufferedAt=new Date();this.purgeExpiredOfflineMessages(direction);while(queue.length>=this.config.queue.offlineBufferSize){const dropped=queue.dequeue();if(!dropped)break;this.logger.message(dropped.id,dropped.direction,'DROPPED')}}if(!queue.enqueue(message)){this.logger.message(message.id,message.direction,'DROPPED');return}this.logger.message(message.id,message.direction,'QUEUED');void this.flushDirection(direction)}
private async flushDirection(direction:MessageDirection):Promise<void>{if(direction==='VP_TO_BC'){if(this.flushingVpToBc)return;this.flushingVpToBc=true}else{if(this.flushingBcToVp)return;this.flushingBcToVp=true}try{const destination=this.getDestinationClient(direction);if(!destination||destination.readyState!==WebSocket.OPEN)return;this.purgeExpiredOfflineMessages(direction);const queue=this.getQueue(direction);while(true){const active=this.getDestinationClient(direction);if(!active||active.readyState!==WebSocket.OPEN)break;const message=queue.peek();if(!message)break;try{await this.send(active,message.payload);queue.dequeue();this.logger.message(message.id,message.direction,'SENT')}catch(err){this.logger.message(message.id,message.direction,'ERROR');this.logger.system(`${this.directionLabel(direction)} SEND ERROR: ${err instanceof Error?err.message:String(err)}`);break}}}finally{if(direction==='VP_TO_BC')this.flushingVpToBc=false;else this.flushingBcToVp=false}}
private handleDestinationDisconnect(direction:MessageDirection):void{const queue=this.getQueue(direction);if(queue.length===0)return;if(this.config.queue.offlineBufferSize===0){while(true){const message=queue.dequeue();if(!message)break;this.logger.message(message.id,message.direction,'DROPPED')}return}const bufferedAt=new Date();const retained:BridgeMessage[]=[];while(true){const message=queue.dequeue();if(!message)break;message.bufferedAt??=bufferedAt;retained.push(message)}const keepFrom=Math.max(0,retained.length-this.config.queue.offlineBufferSize);for(let i=0;i<retained.length;i++){const message=retained[i];if(i<keepFrom)this.logger.message(message.id,message.direction,'DROPPED');else queue.enqueue(message)}}
private purgeExpiredOfflineMessages(direction:MessageDirection):void{const maxAgeMs=this.config.queue.offlineBufferMaxAgeMs;if(maxAgeMs<=0)return;const queue=this.getQueue(direction);const now=Date.now();while(true){const message=queue.peek();if(!message||!message.bufferedAt||now-message.bufferedAt.getTime()<=maxAgeMs)break;queue.dequeue();this.logger.message(message.id,message.direction,'DROPPED')}}private getQueue(direction:MessageDirection):MessageQueue{return direction==='VP_TO_BC'?this.vpToBcQueue:this.bcToVpQueue}private getDestinationClient(direction:MessageDirection):WebSocket|undefined{return direction==='VP_TO_BC'?this.bcClient:this.vpClient}private isDestinationOnline(direction:MessageDirection):boolean{const client=this.getDestinationClient(direction);return!!client&&client.readyState===WebSocket.OPEN}private destinationName(direction:MessageDirection):Side{return direction==='VP_TO_BC'?'BC':'VP'}private directionLabel(direction:MessageDirection):string{return direction==='VP_TO_BC'?'VP→BC':'BC→VP'}private isApiKeyValid(suppliedKey:string):boolean{const expected=this.config.security.apiKey;if(!/^[a-fA-F0-9]{64}$/.test(expected)||suppliedKey.length!==expected.length)return false;try{return crypto.timingSafeEqual(Buffer.from(suppliedKey,'utf8'),Buffer.from(expected,'utf8'))}catch{return false}}private send(ws:WebSocket,payload:string):Promise<void>{return new Promise((resolve,reject)=>ws.send(payload,err=>err?reject(err):resolve()))}}
