import http from 'node:http';
import crypto from 'node:crypto';
import { WebSocketServer,WebSocket } from 'ws';
import { StatusWriter } from '../status/statusWriter';
import type { VPBridgeConfig } from '../config/config';
import { Logger } from '../logging/logger';
import { MailboxStore,type StoredMessage } from './mailboxStore';

const VERSION='0.8.0';
export type GracefulDisconnectReason='shutdown'|'restart'|'exit';
type VppEnvelope={protocolVersion?:number;id?:string;type?:string;from?:string;recipient?:string;to?:string|string[];method?:string;args?:unknown;expectsResponse?:boolean;queue?:{policy?:'fifo'|'replace';key?:string}};
type MemoryMessage=Omit<StoredMessage,'rowId'>;

export class VPBridgeServer {
 private readonly httpServer=http.createServer(); private readonly wsServer=new WebSocketServer({noServer:true}); private readonly store:MailboxStore;
 private readonly clients=new Map<string,WebSocket>(); private readonly memoryQueues=new Map<string,MemoryMessage[]>(); private readonly statusWriter:StatusWriter;
 private nextMessageId=1; private stopping=false;
 constructor(private readonly config:VPBridgeConfig,private readonly logger:Logger){
  this.logger.debug('Initializing Socket Universe Bridge server');
  this.store=new MailboxStore(config); this.statusWriter=new StatusWriter({serverRunning:false,vpConnected:false,bcConnected:false,host:config.server.host,port:config.server.port});
  this.httpServer.on('upgrade',(request,socket,head)=>{try{const url=new URL(request.url??'/',`http://${request.headers.host??'localhost'}`);const mailbox=this.resolveMailbox(url.pathname);if(!mailbox){this.logger.debug(`Rejected unknown mailbox path ${url.pathname}`);socket.write('HTTP/1.1 404 Not Found\r\n\r\n');socket.destroy();return;}
   if(config.server.mode==='all'){const supplied=url.searchParams.get('apiKey')??'';const legacy=(mailbox==='vp'&&url.pathname===config.server.vpPath)||(mailbox==='bc'&&url.pathname===config.server.bcPath);if(!(legacy&&this.isLegacyKeyValid(supplied))&&!this.store.validateApiKey(mailbox,supplied)){this.logger.system(`AUTH REJECTED for ${mailbox} from ${request.socket.remoteAddress??'unknown'}`);this.logger.debug(`Authentication rejected for mailbox ${mailbox}`);socket.write('HTTP/1.1 401 Unauthorized\r\nConnection: close\r\n\r\n');socket.destroy();return;}}
   this.wsServer.handleUpgrade(request,socket,head,ws=>this.wsServer.emit('connection',ws,request,mailbox));}catch(e){this.logger.debug('WebSocket upgrade failed',e);socket.destroy();}});
  this.wsServer.on('connection',(ws:WebSocket,_r:http.IncomingMessage,mailbox:string)=>this.attach(mailbox,ws));
 }
 start():Promise<void>{return new Promise((resolve,reject)=>{this.httpServer.once('error',e=>{this.logger.debug('HTTP server start failed',e);reject(e)});this.httpServer.listen(this.config.server.port,this.config.server.host,()=>{this.httpServer.removeAllListeners('error');this.logger.system(`Socket Universe Bridge v${VERSION} listening on ws://${this.config.server.host}:${this.config.server.port}`);this.logger.debug(`Server listening on ${this.config.server.host}:${this.config.server.port}`);this.updateStatus(true);resolve();});});}
 async stop(reason:GracefulDisconnectReason='shutdown'){if(this.stopping)return;this.stopping=true;this.logger.system(`Stopping SUB (${reason}); announcing graceful disconnect`);this.logger.debug(`Stop requested: ${reason}`);await Promise.allSettled([...this.clients.keys()].map(m=>this.sendServerEvent(m,'disconnecting',{reason})));for(const [,ws] of this.clients)ws.close(1001,`SUB ${reason}`);this.clients.clear();this.memoryQueues.clear();this.wsServer.close();this.updateStatus(false);this.store.close();await new Promise<void>(r=>this.httpServer.close(()=>r()));}
 private resolveMailbox(pathname:string){if(pathname===this.config.server.vpPath)return'vp';if(pathname===this.config.server.bcPath)return'bc';const m=/^\/mailbox\/([a-z0-9]+)$/i.exec(pathname);if(!m)return undefined;return this.store.get(m[1])?.id;}
 private attach(mailbox:string,ws:WebSocket){const old=this.clients.get(mailbox);if(old?.readyState===WebSocket.OPEN)old.close(4000,'Replaced by new mailbox connection');this.clients.set(mailbox,ws);this.logger.system(`${mailbox.toUpperCase()} CONNECTED`);this.logger.debug(`Mailbox connected: ${mailbox}`);this.updateStatus(true);ws.on('message',(d,b)=>{if(!b)this.receive(mailbox,d.toString());});ws.on('close',()=>{if(this.clients.get(mailbox)===ws){this.clients.delete(mailbox);this.logger.system(`${mailbox.toUpperCase()} DISCONNECTED`);this.logger.debug(`Mailbox disconnected: ${mailbox}`);this.updateStatus(true);}});ws.on('error',e=>{this.logger.system(`${mailbox.toUpperCase()} ERROR: ${e.message}`);this.logger.debug(`Mailbox socket error: ${mailbox}`,e)});void this.flush(mailbox);}
 private receive(sender:string,payload:string){let m:VppEnvelope;const logId=this.nextMessageId++;try{m=JSON.parse(payload);}catch(e){this.logger.message(logId,sender,'server','DROPPED',payload);this.logger.debug(`Invalid JSON from ${sender}`,e);return;}const preliminaryTarget=m.recipient??(typeof m.to==='string'?m.to:Array.isArray(m.to)?m.to.join(','):'server');this.logger.message(logId,sender,preliminaryTarget||'server','RECEIVED',payload);
  if(m.protocolVersion!==1||!m.id||!m.type||m.from!==sender){this.serverError(sender,m,'INVALID_MESSAGE','Missing/invalid VPP envelope or from mismatch');return;}if(m.recipient==='server'){this.handleServer(sender,m);return;}
  const targets=this.targets(m);if(targets.length===0){this.serverError(sender,m,'INVALID_ROUTING','No valid recipient');return;}for(const target of targets){if(target.toLowerCase()===sender.toLowerCase()||!this.store.get(target)||!this.store.isAllowed(sender,target)){this.serverError(sender,m,'INVALID_ROUTING',`recipient ${target} is not allowed`);this.logger.debug(`Routing rejected ${sender} -> ${target}`);continue;}const copy={...m,recipient:target};delete copy.to;this.route(sender,target,copy,logId);}}
 private targets(m:VppEnvelope){if(typeof m.recipient==='string'&&m.recipient)return[m.recipient];if(typeof m.to==='string')return[m.to];if(Array.isArray(m.to))return[...new Set(m.to.filter(x=>typeof x==='string'&&x))];return[];}
 private route(source:string,target:string,m:VppEnvelope,logId:number){const payload=JSON.stringify(m);const ws=this.clients.get(target);if(ws?.readyState===WebSocket.OPEN){ws.send(payload);this.logger.message(logId,source,target,'SENT');return;}const box=this.store.get(target)!;if(box.queueMode==='OFF'){this.logger.message(logId,source,target,'DROPPED');return;}const now=Date.now(),expires=box.ttlSeconds===0?null:now+box.ttlSeconds*1000,policy=m.queue?.policy==='replace'?'replace':'fifo',key=policy==='replace'&&typeof m.queue?.key==='string'&&m.queue.key?m.queue.key:null;const q:MemoryMessage={messageId:m.id!,source,target,payload,receivedAt:now,expiresAt:expires,queuePolicy:policy,queueKey:key,expectsResponse:m.expectsResponse===true};
  if(box.queueMode==='PERSISTENT')this.store.storePersistent(q);else{const arr=this.memoryQueues.get(target)??[];if(policy==='replace'&&key){for(let i=arr.length-1;i>=0;i--)if(arr[i].source===source&&arr[i].queuePolicy==='replace'&&arr[i].queueKey===key)arr.splice(i,1);}arr.push(q);this.memoryQueues.set(target,arr);}this.logger.message(logId,source,target,'QUEUED',box.queueMode);}
 private async flush(target:string){const ws=this.clients.get(target);if(!ws||ws.readyState!==WebSocket.OPEN)return;const now=Date.now();const mem=this.memoryQueues.get(target)??[];while(mem.length&&ws.readyState===WebSocket.OPEN){const m=mem.shift()!;if(m.expiresAt!==null&&m.expiresAt<=now)continue;await this.send(ws,m.payload);}this.memoryQueues.set(target,mem);for(const m of this.store.persistentFor(target)){if(ws.readyState!==WebSocket.OPEN)break;try{await this.send(ws,m.payload);this.store.deletePersistent(m.rowId);}catch(e){this.logger.debug(`Persistent queue flush failed for ${target}`,e);break;}}}
 private handleServer(sender:string,m:VppEnvelope){if(m.type!=='call'||m.method!=='ping'||!m.args||typeof m.args!=='object'||Array.isArray(m.args)||Object.keys(m.args as object).length){this.serverError(sender,m,'UNKNOWN_METHOD','Unsupported server request');return;}const boxes:any={};for(const b of this.store.list())boxes[b.id]={connected:this.clients.get(b.id)?.readyState===WebSocket.OPEN};const hb=(this.store.get(sender)?.heartbeatSeconds??30)*1000;this.sendTo(sender,JSON.stringify({protocolVersion:1,id:crypto.randomUUID(),correlationId:m.id,type:'response',from:'server',recipient:sender,result:{mailboxes:boxes,heartbeat:{intervalMs:hb}},source:{app:'SocketUniverseBridge',version:VERSION},timestamp:new Date().toISOString()}));}
 private serverError(sender:string,m:VppEnvelope,code:string,message:string){this.logger.debug(`Server error for ${sender}: ${code} ${message}`);if(!m?.id||m.expectsResponse===false)return;this.sendTo(sender,JSON.stringify({protocolVersion:1,id:crypto.randomUUID(),correlationId:m.id,type:'error',from:'server',recipient:sender,error:{code,message},source:{app:'SocketUniverseBridge',version:VERSION},timestamp:new Date().toISOString()}));}
 private sendServerEvent(mailbox:string,event:string,args:Record<string,unknown>){return this.sendToAsync(mailbox,JSON.stringify({protocolVersion:1,id:crypto.randomUUID(),type:'event',from:'server',recipient:mailbox,event,args,expectsResponse:false,source:{app:'SocketUniverseBridge',version:VERSION},timestamp:new Date().toISOString()}));}
 private sendTo(mailbox:string,payload:string){const ws=this.clients.get(mailbox);if(ws?.readyState===WebSocket.OPEN)ws.send(payload);}
 private sendToAsync(mailbox:string,payload:string){const ws=this.clients.get(mailbox);return !ws||ws.readyState!==WebSocket.OPEN?Promise.resolve():this.send(ws,payload);}
 private send(ws:WebSocket,payload:string){return new Promise<void>((resolve,reject)=>ws.send(payload,e=>e?reject(e):resolve()));}
 private isLegacyKeyValid(key:string){const expected=this.config.security.apiKey;if(!/^[a-fA-F0-9]{64}$/.test(expected)||key.length!==expected.length)return false;try{return crypto.timingSafeEqual(Buffer.from(key),Buffer.from(expected));}catch{return false;}}
 private updateStatus(running:boolean){this.statusWriter.update({serverRunning:running,vpConnected:this.clients.get('vp')?.readyState===WebSocket.OPEN,bcConnected:this.clients.get('bc')?.readyState===WebSocket.OPEN,host:this.config.server.host,port:this.config.server.port});}
}
