using Microsoft.Data.Sqlite;
using System.Security.Cryptography;
using System.Text.RegularExpressions;

namespace VPBridgeTray;

internal sealed class MailboxesForm:Form
{
 readonly string dbPath; readonly ListBox list=new(){Dock=DockStyle.Fill}; readonly TextBox id=new(),friendly=new(),note=new(),key=new(); readonly ComboBox mode=new(){DropDownStyle=ComboBoxStyle.DropDownList}; readonly NumericUpDown ttl=new(){Maximum=864000},heartbeat=new(){Maximum=3600}; readonly CheckedListBox allowed=new(){Height=130,CheckOnClick=true}; readonly Button save=new(){Text="Save",AutoSize=true};
 public MailboxesForm(string path,Icon icon){dbPath=path;Text="Mailboxes";Icon=icon;Width=820;Height=560;StartPosition=FormStartPosition.CenterScreen;mode.Items.AddRange(["OFF","MEMORY","PERSISTENT"]);var split=new SplitContainer{Dock=DockStyle.Fill,SplitterDistance=270};Controls.Add(split);var left=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=2};left.RowStyles.Add(new RowStyle(SizeType.Percent,100));left.RowStyles.Add(new RowStyle(SizeType.AutoSize));left.Controls.Add(list,0,0);var buttons=new FlowLayoutPanel{AutoSize=true};var add=new Button{Text="+",Width=38};var del=new Button{Text="−",Width=38};buttons.Controls.AddRange([add,del]);left.Controls.Add(buttons,0,1);split.Panel1.Controls.Add(left);var form=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(12),ColumnCount=2,AutoScroll=true};form.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,150));form.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));split.Panel2.Controls.Add(form);Add(form,"Technical name",id);Add(form,"Friendly name",friendly);note.MaxLength=255;Add(form,"Note",note);var kp=new FlowLayoutPanel{Dock=DockStyle.Fill,AutoSize=true};key.Width=300;var gen=new Button{Text="Generate",AutoSize=true};kp.Controls.AddRange([key,gen]);Add(form,"API key",kp);Add(form,"Queue mode",mode);Add(form,"TTL [s]",ttl);Add(form,"Heartbeat [s]",heartbeat);Add(form,"Allowed recipients",allowed);form.Controls.Add(save,1,form.RowCount++);list.SelectedIndexChanged+=(_,_)=>LoadSelected();add.Click+=(_,_)=>CreateMailbox();del.Click+=(_,_)=>DeleteMailbox();gen.Click+=(_,_)=>key.Text=Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();save.Click+=(_,_)=>SaveSelected();Shown+=(_,_)=>InitializeDatabase();}
 static void Add(TableLayoutPanel p,string label,Control c){int r=p.RowCount++;p.RowStyles.Add(new RowStyle(SizeType.AutoSize));p.Controls.Add(new Label{Text=label,AutoSize=true,Padding=new Padding(0,7,0,0)},0,r);c.Dock=DockStyle.Top;p.Controls.Add(c,1,r);}
 void InitializeDatabase(){try{EnsureDb();RefreshList();}catch(Exception ex){ShowDatabaseError(ex);}}
 void ShowDatabaseError(Exception ex){var root=ex;while(root.InnerException!=null)root=root.InnerException;MessageBox.Show(this,$"Mailbox database could not be opened.\n\n{root.GetType().Name}: {root.Message}","Mailbox database error",MessageBoxButtons.OK,MessageBoxIcon.Error);Close();}
 SqliteConnection Open(){var c=new SqliteConnection($"Data Source={dbPath}");c.Open();return c;}
 void EnsureDb(){Directory.CreateDirectory(Path.GetDirectoryName(dbPath)!);using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS mailboxes(id TEXT PRIMARY KEY COLLATE NOCASE,friendly_name TEXT NOT NULL,note TEXT NOT NULL DEFAULT '',api_key TEXT NOT NULL DEFAULT '',queue_mode TEXT NOT NULL DEFAULT 'OFF',ttl_seconds INTEGER NOT NULL DEFAULT 0,heartbeat_seconds INTEGER NOT NULL DEFAULT 30); CREATE TABLE IF NOT EXISTS allowed_recipients(source_id TEXT NOT NULL COLLATE NOCASE,target_id TEXT NOT NULL COLLATE NOCASE,PRIMARY KEY(source_id,target_id));";cmd.ExecuteNonQuery();}
 void RefreshList(string? select=null){list.Items.Clear();using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT id,friendly_name FROM mailboxes ORDER BY id COLLATE NOCASE";using var r=cmd.ExecuteReader();while(r.Read())list.Items.Add(new Item(r.GetString(0),r.GetString(1)));if(list.Items.Count>0){int ix=0;if(select!=null)for(int i=0;i<list.Items.Count;i++)if(((Item)list.Items[i]).Id.Equals(select,StringComparison.OrdinalIgnoreCase))ix=i;list.SelectedIndex=ix;}}
 void LoadSelected(){if(list.SelectedItem is not Item it)return;using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT id,friendly_name,note,api_key,queue_mode,ttl_seconds,heartbeat_seconds FROM mailboxes WHERE id=$id";cmd.Parameters.AddWithValue("$id",it.Id);using var r=cmd.ExecuteReader();if(!r.Read())return;id.Text=r.GetString(0);friendly.Text=r.GetString(1);note.Text=r.GetString(2);key.Text=r.GetString(3);mode.SelectedItem=r.GetString(4);ttl.Value=r.GetInt32(5);heartbeat.Value=r.GetInt32(6);allowed.Items.Clear();r.Close();using var all=c.CreateCommand();all.CommandText="SELECT id FROM mailboxes WHERE id<>$id ORDER BY id COLLATE NOCASE";all.Parameters.AddWithValue("$id",it.Id);using var ar=all.ExecuteReader();var ids=new List<string>();while(ar.Read())ids.Add(ar.GetString(0));ar.Close();foreach(var x in ids){using var q=c.CreateCommand();q.CommandText="SELECT 1 FROM allowed_recipients WHERE source_id=$s AND target_id=$t";q.Parameters.AddWithValue("$s",it.Id);q.Parameters.AddWithValue("$t",x);allowed.Items.Add(x,q.ExecuteScalar()!=null);}}
 void CreateMailbox(){string baseId="mailbox";using var c=Open();for(int n=1;;n++){string x=baseId+n;using var q=c.CreateCommand();q.CommandText="SELECT 1 FROM mailboxes WHERE id=$id";q.Parameters.AddWithValue("$id",x);if(q.ExecuteScalar()==null){using var ins=c.CreateCommand();ins.CommandText="INSERT INTO mailboxes(id,friendly_name) VALUES($id,$id)";ins.Parameters.AddWithValue("$id",x);ins.ExecuteNonQuery();RefreshList(x);return;}}}
 void SaveSelected(){if(list.SelectedItem is not Item old)return;var newId=id.Text.Trim().ToLowerInvariant();if(!Regex.IsMatch(newId,"^[a-z0-9]+$")){MessageBox.Show("Technical name may contain only a-z and 0-9.","Invalid mailbox",MessageBoxButtons.OK,MessageBoxIcon.Warning);return;}if(!Regex.IsMatch(key.Text.Trim(),"^[a-fA-F0-9]{64}$")){MessageBox.Show("A non-empty 64-character API key is required. Generate one before saving.","API key required",MessageBoxButtons.OK,MessageBoxIcon.Warning);return;}using var c=Open();using var tx=c.BeginTransaction();using(var q=c.CreateCommand()){q.Transaction=tx;q.CommandText="SELECT 1 FROM mailboxes WHERE id=$n AND id<>$o";q.Parameters.AddWithValue("$n",newId);q.Parameters.AddWithValue("$o",old.Id);if(q.ExecuteScalar()!=null){MessageBox.Show("Technical name must be unique.");return;}}using(var u=c.CreateCommand()){u.Transaction=tx;u.CommandText="UPDATE mailboxes SET id=$n,friendly_name=$f,note=$note,api_key=$k,queue_mode=$m,ttl_seconds=$ttl,heartbeat_seconds=$hb WHERE id=$o";u.Parameters.AddWithValue("$n",newId);u.Parameters.AddWithValue("$f",friendly.Text.Trim());u.Parameters.AddWithValue("$note",note.Text);u.Parameters.AddWithValue("$k",key.Text.Trim().ToLowerInvariant());u.Parameters.AddWithValue("$m",mode.SelectedItem??"OFF");u.Parameters.AddWithValue("$ttl",(int)ttl.Value);u.Parameters.AddWithValue("$hb",(int)heartbeat.Value);u.Parameters.AddWithValue("$o",old.Id);u.ExecuteNonQuery();}using(var d=c.CreateCommand()){d.Transaction=tx;d.CommandText="DELETE FROM allowed_recipients WHERE source_id=$s";d.Parameters.AddWithValue("$s",newId);d.ExecuteNonQuery();}foreach(var x in allowed.CheckedItems.Cast<string>()){using var a=c.CreateCommand();a.Transaction=tx;a.CommandText="INSERT OR IGNORE INTO allowed_recipients(source_id,target_id) VALUES($s,$t)";a.Parameters.AddWithValue("$s",newId);a.Parameters.AddWithValue("$t",x);a.ExecuteNonQuery();}tx.Commit();RefreshList(newId);}
 void DeleteMailbox(){if(list.SelectedItem is not Item it)return;using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT api_key FROM mailboxes WHERE id=$id";q.Parameters.AddWithValue("$id",it.Id);string actual=(q.ExecuteScalar() as string)??"";if(actual.Length==0){MessageBox.Show("This mailbox has no API key. Generate and save an API key before it can be deleted.");return;}string entered=Microsoft.VisualBasic.Interaction.InputBox($"Enter the API key for '{it.Id}' to confirm deletion:","Delete mailbox","");if(entered.Length==0||!CryptographicOperations.FixedTimeEquals(System.Text.Encoding.UTF8.GetBytes(actual),System.Text.Encoding.UTF8.GetBytes(entered))){MessageBox.Show("API key does not match.");return;}using var tx=c.BeginTransaction();foreach(var sql in new[]{"DELETE FROM allowed_recipients WHERE source_id=$id OR target_id=$id","DELETE FROM persistent_queue WHERE source_id=$id OR target_id=$id","DELETE FROM mailboxes WHERE id=$id"}){using var d=c.CreateCommand();d.Transaction=tx;d.CommandText=sql;d.Parameters.AddWithValue("$id",it.Id);try{d.ExecuteNonQuery();}catch(SqliteException){}}tx.Commit();RefreshList();}
 sealed record Item(string Id,string Name){public override string ToString()=>String.IsNullOrWhiteSpace(Name)?Id:$"{Name} [{Id}]";}
}
