using Microsoft.Data.Sqlite;
using System.Globalization;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace VPBridgeTray;

internal sealed class MailboxesForm:Form
{
 readonly string dbPath,statusPath;
 readonly ListView list=new(){Dock=DockStyle.Fill,View=View.Details,HeaderStyle=ColumnHeaderStyle.None,FullRowSelect=true,MultiSelect=false,HideSelection=false};
 readonly TextBox id=new(),name=new(),note=new(),key=new(){ReadOnly=true};
 readonly ComboBox mode=new(){DropDownStyle=ComboBoxStyle.DropDownList};
 readonly NumericUpDown ttl=new(){Maximum=864000},heartbeat=new(){Maximum=3600};
 readonly CheckedListBox allowed=new(){Height=130,CheckOnClick=true};
 readonly Button save=new(){Text="Save",AutoSize=true,Enabled=false},restore=new(){Text="Restore",AutoSize=true,Enabled=false},close=new(){Text="Close",AutoSize=true},regen=new(){Text="↻",Width=30,Height=23,TabStop=false};
 readonly ToolTip tips=new(); readonly System.Windows.Forms.Timer statusTimer=new(){Interval=1000};
 readonly Dictionary<string,bool?> shownStates=new(StringComparer.OrdinalIgnoreCase);
 SplitContainer? split; bool loading,dirty,isNew,selectionGuard; string? originalId; MailboxSnapshot? savedState;
 static readonly Regex IdRx=new("^[a-z0-9_-]+$",RegexOptions.Compiled);

 public MailboxesForm(string path,string status,Icon icon){dbPath=path;statusPath=status;Text="Mailboxes";Icon=icon;Width=900;Height=560;StartPosition=FormStartPosition.CenterScreen;mode.Items.AddRange(["Off","Memory","Persistent"]);BuildUi();WireChanges();Shown+=(_,_)=>InitializeDatabase();FormClosing+=OnClosing;statusTimer.Tick+=(_,_)=>RefreshStatuses();statusTimer.Start();FormClosed+=(_,_)=>statusTimer.Stop();}

 void BuildUi(){
  var outer=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=2,ColumnCount=1,Margin=new Padding(0),Padding=new Padding(8)};outer.RowStyles.Add(new RowStyle(SizeType.Percent,100));outer.RowStyles.Add(new RowStyle(SizeType.AutoSize));Controls.Add(outer);
  split=new SplitContainer{Dock=DockStyle.Fill,FixedPanel=FixedPanel.Panel1,Margin=new Padding(0)};outer.Controls.Add(split,0,0);
  list.Columns.Add("Name",180);list.Columns.Add("Status",28,HorizontalAlignment.Center);split.Panel1.Controls.Add(list);EnableDoubleBuffering(list);

  var form=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(12,8,12,0),ColumnCount=2,AutoScroll=true};form.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));form.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));split.Panel2.Controls.Add(form);
  Add(form,"Name",name);Add(form,"Unique ID",id);
  var kp=new TableLayoutPanel{Dock=DockStyle.Top,ColumnCount=2,AutoSize=true,Margin=new Padding(0)};kp.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));kp.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));key.Dock=DockStyle.Fill;regen.Margin=new Padding(4,0,0,0);kp.Controls.Add(key,0,0);kp.Controls.Add(regen,1,0);Add(form,"API key",kp);
  Add(form,"Queue mode",mode);Add(form,"TTL [s]",ttl);Add(form,"Heartbeat [s]",heartbeat);AddTop(form,"Allowed recipients",allowed);note.MaxLength=255;Add(form,"Note",note);

  var bottom=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,AutoSize=true,Margin=new Padding(0,8,0,0)};bottom.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));bottom.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
  var mailboxButtons=new FlowLayoutPanel{FlowDirection=FlowDirection.LeftToRight,AutoSize=true,WrapContents=false,Margin=new Padding(0)};var add=new Button{Text="+",Width=38};var del=new Button{Text="−",Width=38};mailboxButtons.Controls.AddRange([add,del]);bottom.Controls.Add(mailboxButtons,0,0);
  var editButtons=new FlowLayoutPanel{FlowDirection=FlowDirection.RightToLeft,AutoSize=true,WrapContents=false,Margin=new Padding(0)};editButtons.Controls.Add(close);editButtons.Controls.Add(restore);editButtons.Controls.Add(save);bottom.Controls.Add(editButtons,1,0);outer.Controls.Add(bottom,0,1);

  tips.SetToolTip(name,"Display name of the mailbox. Must be unique, case-insensitive.");tips.SetToolTip(id,"Unique technical ID. Allowed: a-z, 0-9, hyphen and underscore. Must be unique, case-insensitive.");tips.SetToolTip(key,"API key used by clients connecting to this mailbox. It cannot be edited manually.");tips.SetToolTip(regen,"Regenerate API key");tips.SetToolTip(mode,"Queue storage mode: Off, Memory, or Persistent.");tips.SetToolTip(ttl,"Time-to-live for queued messages in seconds. 0 disables expiry.");tips.SetToolTip(heartbeat,"Heartbeat interval in seconds.");tips.SetToolTip(allowed,"Mailboxes this mailbox is allowed to send messages to.");tips.SetToolTip(note,"Optional note for this mailbox.");
  list.SelectedIndexChanged+=(_,_)=>SelectMailbox();add.Click+=(_,_)=>BeginNewMailbox();del.Click+=(_,_)=>DeleteMailbox();regen.Click+=(_,_)=>RegenerateKey();save.Click+=(_,_)=>SaveSelected();restore.Click+=(_,_)=>RestoreSaved();close.Click+=(_,_)=>Close();Resize+=(_,_)=>ResizeListColumns();Shown+=(_,_)=>BeginInvoke((Action)ApplyInitialSplitter);SetEditorEnabled(false);
 }
 static void EnableDoubleBuffering(Control c){try{typeof(Control).GetProperty("DoubleBuffered",BindingFlags.Instance|BindingFlags.NonPublic)?.SetValue(c,true);}catch{}}
 static Label RowLabel(string text)=>new(){Text=text,AutoSize=true,Anchor=AnchorStyles.Left,Margin=new Padding(0,0,12,5)};
 static Label TopLabel(string text)=>new(){Text=text,AutoSize=true,Anchor=AnchorStyles.Left|AnchorStyles.Top,Margin=new Padding(0,3,12,5)};
 static void Add(TableLayoutPanel p,string label,Control c){int r=p.RowCount++;p.RowStyles.Add(new RowStyle(SizeType.AutoSize));p.Controls.Add(RowLabel(label),0,r);c.Dock=DockStyle.Top;c.Margin=new Padding(0,0,0,5);p.Controls.Add(c,1,r);}
 static void AddTop(TableLayoutPanel p,string label,Control c){int r=p.RowCount++;p.RowStyles.Add(new RowStyle(SizeType.AutoSize));p.Controls.Add(TopLabel(label),0,r);c.Dock=DockStyle.Top;c.Margin=new Padding(0,0,0,5);p.Controls.Add(c,1,r);}
 void ApplyInitialSplitter(){if(split==null)return;int w=split.ClientSize.Width;if(w<500)return;split.Panel1MinSize=120;split.Panel2MinSize=360;split.SplitterDistance=Math.Clamp((int)Math.Round(w*.18),split.Panel1MinSize,w-split.Panel2MinSize-split.SplitterWidth);ResizeListColumns();}
 void ResizeListColumns(){if(list.Columns.Count<2)return;list.Columns[1].Width=28;list.Columns[0].Width=Math.Max(70,list.ClientSize.Width-list.Columns[1].Width-4);}

 void WireChanges(){foreach(var tb in new[]{id,name,note})tb.TextChanged+=(_,_)=>UpdateDirtyState();mode.SelectedIndexChanged+=(_,_)=>UpdateDirtyState();ttl.ValueChanged+=(_,_)=>UpdateDirtyState();heartbeat.ValueChanged+=(_,_)=>UpdateDirtyState();allowed.ItemCheck+=(_,_)=>{if(loading)return;BeginInvoke((Action)UpdateDirtyState);};}
 void UpdateDirtyState(){if(loading)return;dirty=isNew||savedState!=null&&!SnapshotEquals(CurrentSnapshot(),savedState);save.Enabled=dirty;restore.Enabled=dirty;}
 static bool SnapshotEquals(MailboxSnapshot a,MailboxSnapshot b)=>a.Id.Equals(b.Id,StringComparison.OrdinalIgnoreCase)&&a.Name==b.Name&&a.Note==b.Note&&a.ApiKey==b.ApiKey&&a.QueueMode.Equals(b.QueueMode,StringComparison.OrdinalIgnoreCase)&&a.Ttl==b.Ttl&&a.Heartbeat==b.Heartbeat&&a.Allowed.OrderBy(x=>x,StringComparer.OrdinalIgnoreCase).SequenceEqual(b.Allowed.OrderBy(x=>x,StringComparer.OrdinalIgnoreCase),StringComparer.OrdinalIgnoreCase);
 MailboxSnapshot CurrentSnapshot()=>new(id.Text.Trim(),name.Text.Trim(),note.Text,key.Text.Trim(),ModeValue(),(int)ttl.Value,(int)heartbeat.Value,allowed.CheckedItems.Cast<RecipientItem>().Select(x=>x.Id).ToArray());
 string ModeValue()=>mode.SelectedIndex switch{1=>"MEMORY",2=>"PERSISTENT",_=>"OFF"};
 static string ModeDisplay(string value)=>value.Equals("MEMORY",StringComparison.OrdinalIgnoreCase)?"Memory":value.Equals("PERSISTENT",StringComparison.OrdinalIgnoreCase)?"Persistent":"Off";
 void SetEditorEnabled(bool enabled){foreach(Control c in new Control[]{id,name,note,key,mode,ttl,heartbeat,allowed,regen})c.Enabled=enabled;save.Enabled=enabled&&dirty;restore.Enabled=enabled&&dirty;}
 void ClearEditor(){loading=true;id.Clear();name.Clear();note.Clear();key.Clear();mode.SelectedIndex=-1;ttl.Value=0;heartbeat.Value=0;allowed.Items.Clear();loading=false;dirty=false;isNew=false;originalId=null;savedState=null;SetEditorEnabled(false);}

 void InitializeDatabase(){try{EnsureDb();RefreshList();ClearEditor();RefreshStatuses();}catch(Exception ex){ShowDatabaseError(ex);}}
 void ShowDatabaseError(Exception ex){var root=ex;while(root.InnerException!=null)root=root.InnerException;MessageBox.Show(this,$"Mailbox database could not be opened.\n\n{root.GetType().Name}: {root.Message}","Mailbox database error",MessageBoxButtons.OK,MessageBoxIcon.Error);Close();}
 SqliteConnection Open(){var c=new SqliteConnection($"Data Source={dbPath}");c.Open();return c;}
 void EnsureDb(){Directory.CreateDirectory(Path.GetDirectoryName(dbPath)!);using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS mailboxes(id TEXT PRIMARY KEY COLLATE NOCASE,friendly_name TEXT NOT NULL COLLATE NOCASE,note TEXT NOT NULL DEFAULT '',api_key TEXT NOT NULL DEFAULT '',queue_mode TEXT NOT NULL DEFAULT 'OFF',ttl_seconds INTEGER NOT NULL DEFAULT 0,heartbeat_seconds INTEGER NOT NULL DEFAULT 30); CREATE UNIQUE INDEX IF NOT EXISTS ux_mailboxes_friendly_name_nocase ON mailboxes(friendly_name COLLATE NOCASE); CREATE TABLE IF NOT EXISTS allowed_recipients(source_id TEXT NOT NULL COLLATE NOCASE,target_id TEXT NOT NULL COLLATE NOCASE,PRIMARY KEY(source_id,target_id));";cmd.ExecuteNonQuery();}
 void RefreshList(string? select=null){loading=true;list.BeginUpdate();list.Items.Clear();shownStates.Clear();using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT id,friendly_name FROM mailboxes ORDER BY friendly_name COLLATE NOCASE,id COLLATE NOCASE";using var r=cmd.ExecuteReader();while(r.Read()){var item=new ListViewItem(r.GetString(1)){Tag=r.GetString(0),UseItemStyleForSubItems=false};var status=item.SubItems.Add("●");status.ForeColor=Color.Gray;status.Font=new Font(Font.FontFamily,10f,FontStyle.Bold);list.Items.Add(item);shownStates[r.GetString(0)]=null;}list.EndUpdate();loading=false;ResizeListColumns();if(select!=null){selectionGuard=true;foreach(ListViewItem x in list.Items)if(((string)x.Tag!).Equals(select,StringComparison.OrdinalIgnoreCase)){x.Selected=true;x.Focused=true;break;}selectionGuard=false;}}
 void RefreshStatuses(){try{var states=new Dictionary<string,bool?>(StringComparer.OrdinalIgnoreCase);if(File.Exists(statusPath)){using var doc=JsonDocument.Parse(File.ReadAllText(statusPath));if(doc.RootElement.TryGetProperty("connections",out var c)&&c.ValueKind==JsonValueKind.Object)foreach(var p in c.EnumerateObject())states[p.Name]=p.Value.ValueKind==JsonValueKind.True?true:p.Value.ValueKind==JsonValueKind.False?false:null;if(doc.RootElement.TryGetProperty("vpConnected",out var vp)&&!states.ContainsKey("vp"))states["vp"]=vp.GetBoolean();if(doc.RootElement.TryGetProperty("bcConnected",out var bc)&&!states.ContainsKey("bc"))states["bc"]=bc.GetBoolean();}foreach(ListViewItem x in list.Items){string mailboxId=(string)x.Tag!;bool? next=states.TryGetValue(mailboxId,out var s)?s:null;if(shownStates.TryGetValue(mailboxId,out var old)&&old==next)continue;shownStates[mailboxId]=next;x.SubItems[1].ForeColor=next==true?Color.ForestGreen:next==false?Color.Firebrick:Color.Gray;}}catch{}}

 bool ConfirmDiscard()=>!dirty||MessageBox.Show(this,"Discard unsaved changes?","Unsaved changes",MessageBoxButtons.YesNo,MessageBoxIcon.Warning,MessageBoxDefaultButton.Button2)==DialogResult.Yes;
 void SelectMailbox(){if(loading||selectionGuard||list.SelectedItems.Count==0)return;string target=(string)list.SelectedItems[0].Tag!;if(!isNew&&originalId!=null&&target.Equals(originalId,StringComparison.OrdinalIgnoreCase))return;if(dirty&&!ConfirmDiscard()){RestoreSelection();return;}LoadMailbox(target);}
 void RestoreSelection(){selectionGuard=true;foreach(ListViewItem x in list.Items)x.Selected=originalId!=null&&((string)x.Tag!).Equals(originalId,StringComparison.OrdinalIgnoreCase);selectionGuard=false;}
 void LoadMailbox(string mailboxId){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT id,friendly_name,note,api_key,queue_mode,ttl_seconds,heartbeat_seconds FROM mailboxes WHERE id=$id";cmd.Parameters.AddWithValue("$id",mailboxId);using var r=cmd.ExecuteReader();if(!r.Read()){ClearEditor();return;}var snap=new MailboxSnapshot(r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetInt32(5),r.GetInt32(6),[]);r.Close();using var a=c.CreateCommand();a.CommandText="SELECT target_id FROM allowed_recipients WHERE source_id=$id ORDER BY target_id COLLATE NOCASE";a.Parameters.AddWithValue("$id",mailboxId);using var ar=a.ExecuteReader();var targets=new HashSet<string>(StringComparer.OrdinalIgnoreCase);while(ar.Read())targets.Add(ar.GetString(0));ar.Close();snap=snap with{Allowed=targets.ToArray()};savedState=snap;originalId=snap.Id;isNew=false;ApplySnapshot(snap);}
 void ApplySnapshot(MailboxSnapshot s){loading=true;id.Text=s.Id;name.Text=s.Name;note.Text=s.Note;key.Text=s.ApiKey;mode.SelectedItem=ModeDisplay(s.QueueMode);ttl.Value=s.Ttl;heartbeat.Value=s.Heartbeat;allowed.Items.Clear();using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT id,friendly_name FROM mailboxes WHERE id<>$id ORDER BY friendly_name COLLATE NOCASE";q.Parameters.AddWithValue("$id",originalId??"");using var r=q.ExecuteReader();while(r.Read()){var targetId=r.GetString(0);allowed.Items.Add(new RecipientItem(targetId,r.GetString(1)),s.Allowed.Contains(targetId,StringComparer.OrdinalIgnoreCase));}loading=false;dirty=false;SetEditorEnabled(true);save.Enabled=false;restore.Enabled=false;}

 void BeginNewMailbox(){if(dirty&&!ConfirmDiscard())return;string entered=Microsoft.VisualBasic.Interaction.InputBox("Enter a unique mailbox name:","New mailbox","").Trim();if(entered.Length==0)return;using var c=Open();if(NameExists(c,entered,null)){MessageBox.Show(this,"A mailbox with this Name already exists.","Duplicate Name",MessageBoxButtons.OK,MessageBoxIcon.Warning);return;}string proposed=Canonicalize(entered);if(proposed.Length==0){MessageBox.Show(this,"The Name cannot be converted to a valid Unique ID.","Invalid Name",MessageBoxButtons.OK,MessageBoxIcon.Warning);return;}if(IdExists(c,proposed,null)){MessageBox.Show(this,$"The proposed Unique ID '{proposed}' already exists. Choose another Name or edit the Unique ID before saving.","Duplicate Unique ID",MessageBoxButtons.OK,MessageBoxIcon.Warning);return;}loading=true;selectionGuard=true;foreach(ListViewItem x in list.Items)x.Selected=false;selectionGuard=false;originalId=null;savedState=null;isNew=true;id.Text=proposed;name.Text=entered;note.Clear();key.Clear();mode.SelectedItem="Off";ttl.Value=0;heartbeat.Value=30;allowed.Items.Clear();using(var q=c.CreateCommand()){q.CommandText="SELECT id,friendly_name FROM mailboxes ORDER BY friendly_name COLLATE NOCASE";using var r=q.ExecuteReader();while(r.Read())allowed.Items.Add(new RecipientItem(r.GetString(0),r.GetString(1)),false);}loading=false;dirty=true;SetEditorEnabled(true);save.Enabled=true;restore.Enabled=true;name.Focus();}
 static string Canonicalize(string value){string normalized=value.Normalize(NormalizationForm.FormD);var sb=new StringBuilder();bool dash=false;foreach(char ch in normalized){if(CharUnicodeInfo.GetUnicodeCategory(ch)==UnicodeCategory.NonSpacingMark)continue;char c=char.ToLowerInvariant(ch);if((c>='a'&&c<='z')||(c>='0'&&c<='9')||c=='_'||c=='-'){sb.Append(c);dash=false;}else if(!dash&&sb.Length>0){sb.Append('-');dash=true;}}return sb.ToString().Trim('-');}
 bool NameExists(SqliteConnection c,string value,string? exceptId){using var q=c.CreateCommand();q.CommandText="SELECT 1 FROM mailboxes WHERE friendly_name=$v COLLATE NOCASE AND ($x IS NULL OR id<>$x COLLATE NOCASE) LIMIT 1";q.Parameters.AddWithValue("$v",value);q.Parameters.AddWithValue("$x",(object?)exceptId??DBNull.Value);return q.ExecuteScalar()!=null;}
 bool IdExists(SqliteConnection c,string value,string? exceptId){using var q=c.CreateCommand();q.CommandText="SELECT 1 FROM mailboxes WHERE id=$v COLLATE NOCASE AND ($x IS NULL OR id<>$x COLLATE NOCASE) LIMIT 1";q.Parameters.AddWithValue("$v",value);q.Parameters.AddWithValue("$x",(object?)exceptId??DBNull.Value);return q.ExecuteScalar()!=null;}
 void RegenerateKey(){if(!key.Enabled)return;if(key.TextLength>0&&MessageBox.Show(this,"Regenerate this API key? The old key will stop working after Save.","Regenerate API key",MessageBoxButtons.YesNo,MessageBoxIcon.Warning,MessageBoxDefaultButton.Button2)!=DialogResult.Yes)return;key.Text=NewKey();UpdateDirtyState();}
 static string NewKey()=>Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();
 void RestoreSaved(){if(!dirty)return;if(isNew){ClearEditor();RestoreSelection();return;}if(savedState!=null)ApplySnapshot(savedState);}

 void SaveSelected(){if(!dirty)return;string finalName=name.Text.Trim(),finalId=id.Text.Trim().ToLowerInvariant();if(finalId.Length==0&&finalName.Length>0){finalId=Canonicalize(finalName);id.Text=finalId;}if(finalName.Length==0&&finalId.Length>0){finalName=finalId;name.Text=finalName;}if(finalName.Length==0||finalId.Length==0){MessageBox.Show(this,"Name and Unique ID cannot both be empty.","Invalid mailbox",MessageBoxButtons.OK,MessageBoxIcon.Warning);return;}if(!IdRx.IsMatch(finalId)){MessageBox.Show(this,"Unique ID may contain only a-z, 0-9, - and _.","Invalid Unique ID",MessageBoxButtons.OK,MessageBoxIcon.Warning);return;}using var c=Open();if(NameExists(c,finalName,isNew?null:originalId)){MessageBox.Show(this,"Name must be unique (case-insensitive).","Duplicate Name",MessageBoxButtons.OK,MessageBoxIcon.Warning);return;}if(IdExists(c,finalId,isNew?null:originalId)){MessageBox.Show(this,"Unique ID must be unique (case-insensitive).","Duplicate Unique ID",MessageBoxButtons.OK,MessageBoxIcon.Warning);return;}string api=key.Text.Trim();if(api.Length==0){api=NewKey();key.Text=api;}if(MessageBox.Show(this,$"Save changes to mailbox '{finalName}'?","Save mailbox",MessageBoxButtons.YesNo,MessageBoxIcon.Question,MessageBoxDefaultButton.Button2)!=DialogResult.Yes)return;using var tx=c.BeginTransaction();if(isNew){using var ins=c.CreateCommand();ins.Transaction=tx;ins.CommandText="INSERT INTO mailboxes(id,friendly_name,note,api_key,queue_mode,ttl_seconds,heartbeat_seconds) VALUES($id,$n,$note,$k,$m,$ttl,$hb)";Fill(ins,finalId,finalName,api);ins.ExecuteNonQuery();}else{using var u=c.CreateCommand();u.Transaction=tx;u.CommandText="UPDATE mailboxes SET id=$id,friendly_name=$n,note=$note,api_key=$k,queue_mode=$m,ttl_seconds=$ttl,heartbeat_seconds=$hb WHERE id=$old";Fill(u,finalId,finalName,api);u.Parameters.AddWithValue("$old",originalId!);u.ExecuteNonQuery();}using(var d=c.CreateCommand()){d.Transaction=tx;d.CommandText="DELETE FROM allowed_recipients WHERE source_id=$s OR source_id=$old";d.Parameters.AddWithValue("$s",finalId);d.Parameters.AddWithValue("$old",originalId??finalId);d.ExecuteNonQuery();}foreach(RecipientItem x in allowed.CheckedItems){using var a=c.CreateCommand();a.Transaction=tx;a.CommandText="INSERT OR IGNORE INTO allowed_recipients(source_id,target_id) VALUES($s,$t)";a.Parameters.AddWithValue("$s",finalId);a.Parameters.AddWithValue("$t",x.Id);a.ExecuteNonQuery();}tx.Commit();RefreshList(finalId);LoadMailbox(finalId);RefreshStatuses();}
 void Fill(SqliteCommand q,string finalId,string finalName,string api){q.Parameters.AddWithValue("$id",finalId);q.Parameters.AddWithValue("$n",finalName);q.Parameters.AddWithValue("$note",note.Text);q.Parameters.AddWithValue("$k",api);q.Parameters.AddWithValue("$m",ModeValue());q.Parameters.AddWithValue("$ttl",(int)ttl.Value);q.Parameters.AddWithValue("$hb",(int)heartbeat.Value);}

 void DeleteMailbox(){if(list.SelectedItems.Count==0||dirty)return;string mailboxId=(string)list.SelectedItems[0].Tag!;using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT api_key,friendly_name FROM mailboxes WHERE id=$id";q.Parameters.AddWithValue("$id",mailboxId);using var r=q.ExecuteReader();if(!r.Read())return;string actual=r.GetString(0),display=r.GetString(1);r.Close();if(actual.Length==0){MessageBox.Show(this,"This mailbox has no API key and cannot be deleted until it is saved with one.");return;}string entered=Microsoft.VisualBasic.Interaction.InputBox($"Enter the API key for '{display}' to confirm deletion:","Delete mailbox","");if(entered.Length==0||!FixedEquals(actual,entered)){MessageBox.Show(this,"API key does not match.");return;}using var tx=c.BeginTransaction();foreach(var sql in new[]{"DELETE FROM allowed_recipients WHERE source_id=$id OR target_id=$id","DELETE FROM persistent_queue WHERE source_id=$id OR target_id=$id","DELETE FROM mailboxes WHERE id=$id"}){using var d=c.CreateCommand();d.Transaction=tx;d.CommandText=sql;d.Parameters.AddWithValue("$id",mailboxId);try{d.ExecuteNonQuery();}catch(SqliteException){}}tx.Commit();RefreshList();ClearEditor();}
 static bool FixedEquals(string a,string b){var x=Encoding.UTF8.GetBytes(a);var y=Encoding.UTF8.GetBytes(b);return x.Length==y.Length&&CryptographicOperations.FixedTimeEquals(x,y);}
 void OnClosing(object? sender,FormClosingEventArgs e){if(dirty&&!ConfirmDiscard())e.Cancel=true;}
 sealed record MailboxSnapshot(string Id,string Name,string Note,string ApiKey,string QueueMode,int Ttl,int Heartbeat,string[] Allowed);
 sealed record RecipientItem(string Id,string Name){public override string ToString()=>String.IsNullOrWhiteSpace(Name)?Id:Name;}
}
