using Microsoft.Data.Sqlite;
using System.Globalization;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace VPBridgeTray;

internal sealed class MailboxesForm:Form
{
 readonly string dbPath,statusPath;
 readonly ListView list=new(){Dock=DockStyle.Fill,View=View.Details,HeaderStyle=ColumnHeaderStyle.None,FullRowSelect=true,MultiSelect=false,HideSelection=false,OwnerDraw=true};
 readonly TextBox id=new(),name=new(),note=new(){Multiline=true,MaxLength=255,Height=76,ScrollBars=ScrollBars.Vertical,AcceptsReturn=true},key=new(){ReadOnly=true};
 readonly ComboBox mode=new(){DropDownStyle=ComboBoxStyle.DropDownList};
 readonly NumericUpDown ttl=new(){Maximum=864000},heartbeat=new(){Maximum=3600};
 readonly CheckedListBox allowed=new(){Height=130,CheckOnClick=true};
 readonly Button save=new(){Text="Save",AutoSize=true,Enabled=false},restore=new(){Text="Restore",AutoSize=true,Enabled=false},close=new(){Text="Close",AutoSize=true},regen=new(){Text="↻",Width=30,Height=23,TabStop=false},copyId=new(){Text="⧉",Width=30,Height=23,TabStop=false},copyKey=new(){Text="⧉",Width=30,Height=23,TabStop=false},add=new(){Text="+",Width=38},del=new(){Text="−",Width=38};
 readonly ToolTip tips=new(); readonly System.Windows.Forms.Timer statusTimer=new(){Interval=1000}; readonly Dictionary<string,bool?> shownStates=new(StringComparer.OrdinalIgnoreCase);
 SplitContainer? split; bool loading,dirty,isNew,selectionGuard; string? originalId; MailboxSnapshot? savedState;
 static readonly Regex IdRx=new("^[a-z0-9_-]+$",RegexOptions.Compiled);
 const int StatusColumnWidth=18;
 public MailboxesForm(string path,string status,Icon icon){dbPath=path;statusPath=status;Text="Mailboxes";Icon=icon;Width=900;Height=560;StartPosition=FormStartPosition.CenterScreen;mode.Items.AddRange(["Off","Memory","Persistent"]);BuildUi();WireChanges();Shown+=(_,_)=>InitializeDatabase();FormClosing+=OnClosing;statusTimer.Tick+=(_,_)=>RefreshStatuses();statusTimer.Start();FormClosed+=(_,_)=>statusTimer.Stop();}

 void BuildUi(){var outer=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=2,ColumnCount=1,Padding=new Padding(8)};outer.RowStyles.Add(new RowStyle(SizeType.Percent,100));outer.RowStyles.Add(new RowStyle(SizeType.AutoSize));Controls.Add(outer);split=new SplitContainer{Dock=DockStyle.Fill,FixedPanel=FixedPanel.Panel1};outer.Controls.Add(split,0,0);list.Columns.Add("Name",180);list.Columns.Add("Status",StatusColumnWidth,HorizontalAlignment.Center);split.Panel1.Controls.Add(list);EnableDoubleBuffering(list);
  var form=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(12,8,12,0),ColumnCount=2,AutoScroll=true};form.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));form.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));split.Panel2.Controls.Add(form);
  Add(form,"Name",name,"Display name of the mailbox. Must be unique.");Add(form,"Service Name",ButtonRow(id,copyId),"Service identifier. Allowed: a-z, 0-9, - and _. Comparison is case-insensitive.");Add(form,"API key",ButtonRow(key,regen,copyKey),"API key used by clients. It cannot be edited manually.");Add(form,"Queue mode",mode,"Queue storage mode: Off, Memory, or Persistent.");Add(form,"TTL [s]",ttl,"Time-to-live for queued messages in seconds. 0 disables expiry.");Add(form,"Heartbeat [s]",heartbeat,"Heartbeat interval in seconds.");AddTop(form,"Allowed recipients",allowed,"Mailboxes this mailbox is allowed to send messages to.");AddTop(form,"Note",note,"Optional note. Maximum 255 characters.");tips.SetToolTip(copyId,"Copy Service Name");tips.SetToolTip(copyKey,"Copy API key");tips.SetToolTip(regen,"Regenerate API key");
  var bottom=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,AutoSize=true,Margin=new Padding(0,8,0,0)};bottom.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));bottom.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));var mb=new FlowLayoutPanel{AutoSize=true,WrapContents=false};mb.Controls.AddRange([add,del]);bottom.Controls.Add(mb,0,0);var eb=new FlowLayoutPanel{AutoSize=true,WrapContents=false};eb.Controls.AddRange([save,restore,close]);bottom.Controls.Add(eb,1,0);outer.Controls.Add(bottom,0,1);
  list.SelectedIndexChanged+=(_,_)=>SelectMailbox();list.DrawItem+=(_,_)=>{};list.DrawSubItem+=DrawMailboxSubItem;add.Click+=(_,_)=>BeginNewMailbox();del.Click+=(_,_)=>DeleteMailbox();regen.Click+=(_,_)=>RegenerateKey();copyId.Click+=(_,_)=>Copy(id.Text);copyKey.Click+=(_,_)=>Copy(key.Text);save.Click+=(_,_)=>SaveSelected();restore.Click+=(_,_)=>RestoreSaved();close.Click+=(_,_)=>Close();Resize+=(_,_)=>ResizeListColumns();split.SplitterMoved+=(_,_)=>ResizeListColumns();split.Panel1.Resize+=(_,_)=>ResizeListColumns();Shown+=(_,_)=>BeginInvoke((Action)ApplyInitialSplitter);SetEditorEnabled(false);}
 void DrawMailboxSubItem(object? sender,DrawListViewSubItemEventArgs e){bool selected=e.Item.Selected;Color back=selected?SystemColors.Highlight:SystemColors.Window;e.Graphics.FillRectangle(new SolidBrush(back),e.Bounds);if(e.ColumnIndex==1){string mid=(string)e.Item.Tag!;bool? state=shownStates.TryGetValue(mid,out var s)?s:null;Color dot=state==true?Color.ForestGreen:state==false?Color.Firebrick:Color.Gray;int d=6,x=e.Bounds.Left+(e.Bounds.Width-d)/2,y=e.Bounds.Top+(e.Bounds.Height-d)/2;using var b=new SolidBrush(dot);e.Graphics.FillEllipse(b,x,y,d,d);return;}bool current=originalId!=null&&((string)e.Item.Tag!).Equals(originalId,StringComparison.OrdinalIgnoreCase);Color fore=selected?SystemColors.HighlightText:dirty&&!current?SystemColors.GrayText:SystemColors.WindowText;TextRenderer.DrawText(e.Graphics,e.SubItem.Text,list.Font,e.Bounds,fore,back,TextFormatFlags.Left|TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis|TextFormatFlags.NoPrefix);}
 Control ButtonRow(Control field,params Button[] buttons){var p=new TableLayoutPanel{Dock=DockStyle.Top,ColumnCount=buttons.Length+1,AutoSize=true,Margin=new Padding(0)};p.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));field.Dock=DockStyle.Fill;p.Controls.Add(field,0,0);for(int i=0;i<buttons.Length;i++){p.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));buttons[i].Margin=new Padding(4,0,0,0);p.Controls.Add(buttons[i],i+1,0);}return p;}
 static void EnableDoubleBuffering(Control c){try{typeof(Control).GetProperty("DoubleBuffered",BindingFlags.Instance|BindingFlags.NonPublic)?.SetValue(c,true);}catch{}}
 void Add(TableLayoutPanel p,string label,Control c,string tip)=>AddCore(p,label,c,tip,false);void AddTop(TableLayoutPanel p,string label,Control c,string tip)=>AddCore(p,label,c,tip,true);
 void AddCore(TableLayoutPanel p,string text,Control c,string tip,bool top){int r=p.RowCount++;p.RowStyles.Add(new RowStyle(SizeType.AutoSize));var l=new Label{Text=text,AutoSize=true,Anchor=top?AnchorStyles.Left|AnchorStyles.Top:AnchorStyles.Left,Margin=new Padding(0,top?3:0,12,5)};p.Controls.Add(l,0,r);c.Dock=DockStyle.Top;c.Margin=new Padding(0,0,0,5);p.Controls.Add(c,1,r);tips.SetToolTip(l,tip);tips.SetToolTip(c,tip);}
 void ApplyInitialSplitter(){if(split==null)return;int w=split.ClientSize.Width;if(w<500)return;split.Panel1MinSize=120;split.Panel2MinSize=360;split.SplitterDistance=Math.Clamp((int)Math.Round(w*.18),split.Panel1MinSize,w-split.Panel2MinSize-split.SplitterWidth);ResizeListColumns();}
 void ResizeListColumns(){if(list.Columns.Count<2)return;list.Columns[1].Width=StatusColumnWidth;list.Columns[0].Width=Math.Max(70,list.ClientSize.Width-StatusColumnWidth-4);list.Invalidate();}
 void Copy(string text){if(text.Length>0)Clipboard.SetText(text);}

 void WireChanges(){foreach(var tb in new[]{id,name,note})tb.TextChanged+=(_,_)=>UpdateDirtyState();mode.SelectedIndexChanged+=(_,_)=>UpdateDirtyState();ttl.ValueChanged+=(_,_)=>UpdateDirtyState();heartbeat.ValueChanged+=(_,_)=>UpdateDirtyState();allowed.ItemCheck+=(_,_)=>{if(!loading)BeginInvoke((Action)UpdateDirtyState);};}
 void UpdateDirtyState(){if(loading)return;dirty=isNew||savedState!=null&&!SnapshotEquals(CurrentSnapshot(),savedState);save.Enabled=dirty;restore.Enabled=dirty;add.Enabled=!dirty;del.Enabled=!dirty&&list.SelectedItems.Count>0;SetListLocked(dirty);if(dirty&&!isNew)RestoreSelection();}
 void SetListLocked(bool locked){list.Invalidate();}
 static bool SnapshotEquals(MailboxSnapshot a,MailboxSnapshot b)=>a.Id.Equals(b.Id,StringComparison.OrdinalIgnoreCase)&&a.Name==b.Name&&a.Note==b.Note&&a.ApiKey==b.ApiKey&&a.QueueMode.Equals(b.QueueMode,StringComparison.OrdinalIgnoreCase)&&a.Ttl==b.Ttl&&a.Heartbeat==b.Heartbeat&&a.Allowed.OrderBy(x=>x,StringComparer.OrdinalIgnoreCase).SequenceEqual(b.Allowed.OrderBy(x=>x,StringComparer.OrdinalIgnoreCase),StringComparer.OrdinalIgnoreCase);
 MailboxSnapshot CurrentSnapshot()=>new(id.Text.Trim(),name.Text.Trim(),note.Text,key.Text.Trim(),ModeValue(),(int)ttl.Value,(int)heartbeat.Value,allowed.CheckedItems.Cast<RecipientItem>().Select(x=>x.Id).ToArray());
 string ModeValue()=>mode.SelectedIndex switch{1=>"MEMORY",2=>"PERSISTENT",_=>"OFF"};static string ModeDisplay(string v)=>v.Equals("MEMORY",StringComparison.OrdinalIgnoreCase)?"Memory":v.Equals("PERSISTENT",StringComparison.OrdinalIgnoreCase)?"Persistent":"Off";
 void SetEditorEnabled(bool enabled){foreach(Control c in new Control[]{id,name,note,key,mode,ttl,heartbeat,allowed,regen,copyId,copyKey})c.Enabled=enabled;save.Enabled=enabled&&dirty;restore.Enabled=enabled&&dirty;add.Enabled=!dirty;del.Enabled=!dirty&&list.SelectedItems.Count>0;}
 void ClearEditor(){loading=true;id.Clear();name.Clear();note.Clear();key.Clear();mode.SelectedIndex=-1;ttl.Value=0;heartbeat.Value=0;allowed.Items.Clear();loading=false;dirty=false;isNew=false;originalId=null;savedState=null;SetEditorEnabled(false);SetListLocked(false);}

 void InitializeDatabase(){try{EnsureDb();RefreshList();if(list.Items.Count>0)SelectIndex(0);else ClearEditor();RefreshStatuses();}catch(Exception ex){ShowDatabaseError(ex);}}
 void ShowDatabaseError(Exception ex){var root=ex;while(root.InnerException!=null)root=root.InnerException;MessageBox.Show(this,$"Mailbox database could not be opened.\n\n{root.GetType().Name}: {root.Message}","Mailbox database error",MessageBoxButtons.OK,MessageBoxIcon.Error);Close();}
 SqliteConnection Open(){var c=new SqliteConnection($"Data Source={dbPath}");c.Open();return c;}
 void EnsureDb(){Directory.CreateDirectory(Path.GetDirectoryName(dbPath)!);using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS mailboxes(id TEXT PRIMARY KEY COLLATE NOCASE,friendly_name TEXT NOT NULL COLLATE NOCASE,note TEXT NOT NULL DEFAULT '',api_key TEXT NOT NULL DEFAULT '',queue_mode TEXT NOT NULL DEFAULT 'OFF',ttl_seconds INTEGER NOT NULL DEFAULT 0,heartbeat_seconds INTEGER NOT NULL DEFAULT 30); CREATE UNIQUE INDEX IF NOT EXISTS ux_mailboxes_friendly_name_nocase ON mailboxes(friendly_name COLLATE NOCASE); CREATE TABLE IF NOT EXISTS allowed_recipients(source_id TEXT NOT NULL COLLATE NOCASE,target_id TEXT NOT NULL COLLATE NOCASE,PRIMARY KEY(source_id,target_id));";cmd.ExecuteNonQuery();}
 void RefreshList(string? select=null){loading=true;list.BeginUpdate();list.Items.Clear();shownStates.Clear();using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT id,friendly_name FROM mailboxes ORDER BY friendly_name COLLATE NOCASE,id COLLATE NOCASE";using var r=cmd.ExecuteReader();while(r.Read()){string mid=r.GetString(0);var item=new ListViewItem(r.GetString(1)){Tag=mid,UseItemStyleForSubItems=false};item.SubItems.Add("");list.Items.Add(item);shownStates[mid]=null;}list.EndUpdate();loading=false;ResizeListColumns();if(select!=null)SelectById(select);}
 void SelectIndex(int i){if(i<0||i>=list.Items.Count)return;selectionGuard=true;foreach(ListViewItem x in list.Items)x.Selected=false;list.Items[i].Selected=true;list.Items[i].Focused=true;selectionGuard=false;LoadMailbox((string)list.Items[i].Tag!);}
 void SelectById(string value){for(int i=0;i<list.Items.Count;i++)if(((string)list.Items[i].Tag!).Equals(value,StringComparison.OrdinalIgnoreCase)){SelectIndex(i);return;}}
 void RefreshStatuses(){try{var states=new Dictionary<string,bool?>(StringComparer.OrdinalIgnoreCase);if(File.Exists(statusPath)){using var doc=JsonDocument.Parse(File.ReadAllText(statusPath));if(doc.RootElement.TryGetProperty("connections",out var c)&&c.ValueKind==JsonValueKind.Object)foreach(var p in c.EnumerateObject())states[p.Name]=p.Value.ValueKind==JsonValueKind.True?true:p.Value.ValueKind==JsonValueKind.False?false:null;if(doc.RootElement.TryGetProperty("vpConnected",out var vp))states.TryAdd("vp",vp.GetBoolean());if(doc.RootElement.TryGetProperty("bcConnected",out var bc))states.TryAdd("bc",bc.GetBoolean());}bool changed=false;foreach(ListViewItem x in list.Items){string mid=(string)x.Tag!;bool? next=states.TryGetValue(mid,out var s)?s:null;if(shownStates.TryGetValue(mid,out var old)&&old==next)continue;shownStates[mid]=next;changed=true;}if(changed)list.Invalidate();}catch{}}

 bool ConfirmDiscard()=>!dirty||MessageBox.Show(this,"Discard unsaved changes?","Unsaved changes",MessageBoxButtons.YesNo,MessageBoxIcon.Warning,MessageBoxDefaultButton.Button2)==DialogResult.Yes;
 void SelectMailbox(){if(loading||selectionGuard)return;if(dirty){RestoreSelection();return;}if(list.SelectedItems.Count==0)return;string target=(string)list.SelectedItems[0].Tag!;if(originalId!=null&&target.Equals(originalId,StringComparison.OrdinalIgnoreCase))return;LoadMailbox(target);}
 void RestoreSelection(){if(isNew||originalId==null)return;selectionGuard=true;ListViewItem? current=null;foreach(ListViewItem x in list.Items){bool match=((string)x.Tag!).Equals(originalId,StringComparison.OrdinalIgnoreCase);x.Selected=match;if(match){x.Focused=true;current=x;}}selectionGuard=false;if(current!=null){current.EnsureVisible();list.Invalidate();}}
 void LoadMailbox(string mailboxId){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT id,friendly_name,note,api_key,queue_mode,ttl_seconds,heartbeat_seconds FROM mailboxes WHERE id=$id";cmd.Parameters.AddWithValue("$id",mailboxId);using var r=cmd.ExecuteReader();if(!r.Read()){ClearEditor();return;}var snap=new MailboxSnapshot(r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetInt32(5),r.GetInt32(6),[]);r.Close();using var a=c.CreateCommand();a.CommandText="SELECT target_id FROM allowed_recipients WHERE source_id=$id ORDER BY target_id COLLATE NOCASE";a.Parameters.AddWithValue("$id",mailboxId);using var ar=a.ExecuteReader();var targets=new HashSet<string>(StringComparer.OrdinalIgnoreCase);while(ar.Read())targets.Add(ar.GetString(0));snap=snap with{Allowed=targets.ToArray()};savedState=snap;originalId=snap.Id;isNew=false;ApplySnapshot(snap);}
 void ApplySnapshot(MailboxSnapshot s){loading=true;id.Text=s.Id;name.Text=s.Name;note.Text=s.Note;key.Text=s.ApiKey;mode.SelectedItem=ModeDisplay(s.QueueMode);ttl.Value=s.Ttl;heartbeat.Value=s.Heartbeat;allowed.Items.Clear();using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT id,friendly_name FROM mailboxes WHERE id<>$id ORDER BY friendly_name COLLATE NOCASE";q.Parameters.AddWithValue("$id",originalId??"");using var r=q.ExecuteReader();while(r.Read()){string tid=r.GetString(0);allowed.Items.Add(new RecipientItem(tid,r.GetString(1)),s.Allowed.Contains(tid,StringComparer.OrdinalIgnoreCase));}loading=false;dirty=false;SetEditorEnabled(true);SetListLocked(false);RestoreSelection();del.Enabled=list.SelectedItems.Count>0;}

 void BeginNewMailbox(){if(dirty)return;using var c=Open();using var dlg=new NewMailboxDialog(c,Canonicalize,NameExists,IdExists,Icon??SystemIcons.Application);if(dlg.ShowDialog(this)!=DialogResult.OK)return;loading=true;selectionGuard=true;foreach(ListViewItem x in list.Items)x.Selected=false;selectionGuard=false;originalId=null;savedState=null;isNew=true;id.Text=dlg.ServiceName;name.Text=dlg.MailboxName;note.Clear();key.Clear();mode.SelectedItem="Off";ttl.Value=0;heartbeat.Value=30;allowed.Items.Clear();using(var q=c.CreateCommand()){q.CommandText="SELECT id,friendly_name FROM mailboxes ORDER BY friendly_name COLLATE NOCASE";using var r=q.ExecuteReader();while(r.Read())allowed.Items.Add(new RecipientItem(r.GetString(0),r.GetString(1)),false);}loading=false;UpdateDirtyState();name.Focus();}
 static string Canonicalize(string value){string normalized=value.Normalize(NormalizationForm.FormD);var sb=new StringBuilder();bool dash=false;foreach(char ch in normalized){if(CharUnicodeInfo.GetUnicodeCategory(ch)==UnicodeCategory.NonSpacingMark)continue;char c=char.ToLowerInvariant(ch);if((c>='a'&&c<='z')||(c>='0'&&c<='9')||c=='_'||c=='-'){sb.Append(c);dash=false;}else if(!dash&&sb.Length>0){sb.Append('-');dash=true;}}return sb.ToString().Trim('-');}
 static string FilterServiceName(string value){var sb=new StringBuilder();foreach(char c0 in value.ToLowerInvariant()){char c=c0;if((c>='a'&&c<='z')||(c>='0'&&c<='9')||c=='_'||c=='-')sb.Append(c);}return sb.ToString();}
 bool NameExists(SqliteConnection c,string v,string? except){using var q=c.CreateCommand();q.CommandText="SELECT 1 FROM mailboxes WHERE friendly_name=$v COLLATE NOCASE AND ($x IS NULL OR id<>$x COLLATE NOCASE) LIMIT 1";q.Parameters.AddWithValue("$v",v);q.Parameters.AddWithValue("$x",(object?)except??DBNull.Value);return q.ExecuteScalar()!=null;}
 bool IdExists(SqliteConnection c,string v,string? except){using var q=c.CreateCommand();q.CommandText="SELECT 1 FROM mailboxes WHERE id=$v COLLATE NOCASE AND ($x IS NULL OR id<>$x COLLATE NOCASE) LIMIT 1";q.Parameters.AddWithValue("$v",v);q.Parameters.AddWithValue("$x",(object?)except??DBNull.Value);return q.ExecuteScalar()!=null;}
 void RegenerateKey(){if(!key.Enabled)return;if(key.TextLength>0&&MessageBox.Show(this,"Regenerate this API key?\nThe old key will stop working after Save.","Regenerate API key",MessageBoxButtons.YesNo,MessageBoxIcon.Warning,MessageBoxDefaultButton.Button2)!=DialogResult.Yes)return;key.Text=NewKey();UpdateDirtyState();}
 static string NewKey()=>Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();
 void RestoreSaved(){if(!dirty)return;if(isNew){ClearEditor();if(list.Items.Count>0)SelectIndex(0);return;}if(savedState!=null){ApplySnapshot(savedState);RestoreSelection();del.Enabled=list.SelectedItems.Count>0;}}

 void SaveSelected(){if(!dirty)return;string finalName=name.Text.Trim(),finalId=id.Text.Trim().ToLowerInvariant();if(finalId.Length==0&&finalName.Length>0){finalId=Canonicalize(finalName);id.Text=finalId;}if(finalName.Length==0&&finalId.Length>0){finalName=finalId;name.Text=finalName;}if(finalName.Length==0||finalId.Length==0){Warn("Name and Service Name cannot both be empty.","Invalid mailbox");return;}if(!IdRx.IsMatch(finalId)){Warn("Service Name may contain only a-z, 0-9, - and _.","Invalid Service Name");return;}using var c=Open();if(NameExists(c,finalName,isNew?null:originalId)){Warn("Name must be unique.","Duplicate Name");return;}if(IdExists(c,finalId,isNew?null:originalId)){Warn("Service Name must be unique.","Duplicate Service Name");return;}string api=key.Text.Trim();if(api.Length==0){api=NewKey();key.Text=api;}if(MessageBox.Show(this,$"Save changes to mailbox '{finalName}'?","Save mailbox",MessageBoxButtons.YesNo,MessageBoxIcon.Question,MessageBoxDefaultButton.Button2)!=DialogResult.Yes)return;using var tx=c.BeginTransaction();if(isNew){using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT INTO mailboxes(id,friendly_name,note,api_key,queue_mode,ttl_seconds,heartbeat_seconds) VALUES($id,$n,$note,$k,$m,$ttl,$hb)";Fill(q,finalId,finalName,api);q.ExecuteNonQuery();}else{using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="UPDATE mailboxes SET id=$id,friendly_name=$n,note=$note,api_key=$k,queue_mode=$m,ttl_seconds=$ttl,heartbeat_seconds=$hb WHERE id=$old";Fill(q,finalId,finalName,api);q.Parameters.AddWithValue("$old",originalId!);q.ExecuteNonQuery();}using(var d=c.CreateCommand()){d.Transaction=tx;d.CommandText="DELETE FROM allowed_recipients WHERE source_id=$s OR source_id=$old";d.Parameters.AddWithValue("$s",finalId);d.Parameters.AddWithValue("$old",originalId??finalId);d.ExecuteNonQuery();}foreach(RecipientItem x in allowed.CheckedItems){using var a=c.CreateCommand();a.Transaction=tx;a.CommandText="INSERT OR IGNORE INTO allowed_recipients(source_id,target_id) VALUES($s,$t)";a.Parameters.AddWithValue("$s",finalId);a.Parameters.AddWithValue("$t",x.Id);a.ExecuteNonQuery();}tx.Commit();RefreshList(finalId);LoadMailbox(finalId);RefreshStatuses();}
 void Fill(SqliteCommand q,string fid,string fn,string api){q.Parameters.AddWithValue("$id",fid);q.Parameters.AddWithValue("$n",fn);q.Parameters.AddWithValue("$note",note.Text);q.Parameters.AddWithValue("$k",api);q.Parameters.AddWithValue("$m",ModeValue());q.Parameters.AddWithValue("$ttl",(int)ttl.Value);q.Parameters.AddWithValue("$hb",(int)heartbeat.Value);}

 void DeleteMailbox(){if(list.SelectedItems.Count==0||dirty)return;int oldIndex=list.SelectedItems[0].Index;string mailboxId=(string)list.SelectedItems[0].Tag!;using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT api_key,friendly_name FROM mailboxes WHERE id=$id";q.Parameters.AddWithValue("$id",mailboxId);using var r=q.ExecuteReader();if(!r.Read())return;string actual=r.GetString(0),display=r.GetString(1);r.Close();if(actual.Length==0){Warn("This mailbox has no API key.\nSave the mailbox before deleting it.","Delete mailbox");return;}using var dlg=new DeleteMailboxDialog(display,actual,Icon??SystemIcons.Application);if(dlg.ShowDialog(this)!=DialogResult.OK)return;using var tx=c.BeginTransaction();foreach(var sql in new[]{"DELETE FROM allowed_recipients WHERE source_id=$id OR target_id=$id","DELETE FROM persistent_queue WHERE source_id=$id OR target_id=$id","DELETE FROM mailboxes WHERE id=$id"}){using var d=c.CreateCommand();d.Transaction=tx;d.CommandText=sql;d.Parameters.AddWithValue("$id",mailboxId);try{d.ExecuteNonQuery();}catch(SqliteException){}}tx.Commit();RefreshList();if(list.Items.Count==0)ClearEditor();else SelectIndex(Math.Min(oldIndex,list.Items.Count-1));RefreshStatuses();}
 static bool FixedEquals(string a,string b){var x=Encoding.UTF8.GetBytes(a);var y=Encoding.UTF8.GetBytes(b);return x.Length==y.Length&&CryptographicOperations.FixedTimeEquals(x,y);}
 void Warn(string text,string title)=>MessageBox.Show(this,text,title,MessageBoxButtons.OK,MessageBoxIcon.Warning);
 void OnClosing(object? s,FormClosingEventArgs e){if(dirty&&!ConfirmDiscard())e.Cancel=true;}
 sealed record MailboxSnapshot(string Id,string Name,string Note,string ApiKey,string QueueMode,int Ttl,int Heartbeat,string[] Allowed);sealed record RecipientItem(string Id,string Name){public override string ToString()=>string.IsNullOrWhiteSpace(Name)?Id:Name;}

 sealed class NewMailboxDialog:Form{readonly TextBox n=new(),s=new();readonly Button create=new(){Text="Create",Enabled=false,AutoSize=true},cancel=new(){Text="Cancel",AutoSize=true};readonly Label err=new(){AutoSize=true,ForeColor=Color.Firebrick};readonly SqliteConnection db;readonly Func<string,string> canon;readonly Func<SqliteConnection,string,string?,bool> nameExists,idExists;bool filtering;public string MailboxName=>n.Text.Trim();public string ServiceName=>s.Text.Trim().ToLowerInvariant();public NewMailboxDialog(SqliteConnection c,Func<string,string> ca,Func<SqliteConnection,string,string?,bool> ne,Func<SqliteConnection,string,string?,bool> ie,Icon icon){db=c;canon=ca;nameExists=ne;idExists=ie;Icon=icon;Text="New mailbox";StartPosition=FormStartPosition.CenterParent;FormBorderStyle=FormBorderStyle.FixedDialog;MinimizeBox=false;MaximizeBox=false;ClientSize=new Size(390,150);var p=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(12),ColumnCount=2,RowCount=4};p.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));p.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));var ln=new Label{Text="Name",AutoSize=true,Anchor=AnchorStyles.Left};var ls=new Label{Text="Service Name",AutoSize=true,Anchor=AnchorStyles.Left};n.Dock=DockStyle.Fill;s.Dock=DockStyle.Fill;p.Controls.Add(ln,0,0);p.Controls.Add(n,1,0);p.Controls.Add(ls,0,1);p.Controls.Add(s,1,1);p.Controls.Add(err,1,2);var host=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,AutoSize=true};host.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));host.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));host.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));var b=new FlowLayoutPanel{AutoSize=true,WrapContents=false};b.Controls.AddRange([create,cancel]);host.Controls.Add(b,1,0);p.Controls.Add(host,0,3);p.SetColumnSpan(host,2);Controls.Add(p);create.DialogResult=DialogResult.OK;cancel.DialogResult=DialogResult.Cancel;AcceptButton=create;CancelButton=cancel;bool auto=true;n.TextChanged+=(_,_)=>{if(auto)s.Text=canon(n.Text);ValidateNow();};s.TextChanged+=(_,_)=>{if(filtering)return;string filtered=FilterServiceName(s.Text);if(filtered!=s.Text){filtering=true;int pos=Math.Min(s.SelectionStart,filtered.Length);s.Text=filtered;s.SelectionStart=pos;filtering=false;}auto=s.Text==canon(n.Text);ValidateNow();};ValidateNow();}void ValidateNow(){string nn=n.Text.Trim(),ss=s.Text.Trim().ToLowerInvariant();string e=nn.Length==0?"Name is required.":ss.Length==0?"Service Name is required.":nameExists(db,nn,null)?"Name already exists.":idExists(db,ss,null)?"Service Name already exists.":"";err.Text=e;create.Enabled=e.Length==0;}}
 sealed class DeleteMailboxDialog:Form{readonly TextBox input=new();readonly Button delBtn=new(){Text="Delete",Enabled=false,AutoSize=true},cancel=new(){Text="Cancel",AutoSize=true};readonly Label invalid=new(){Text="",AutoSize=true,ForeColor=Color.Firebrick};readonly string actual;public DeleteMailboxDialog(string name,string api,Icon icon){actual=api;Icon=icon;Text="Delete mailbox";StartPosition=FormStartPosition.CenterParent;FormBorderStyle=FormBorderStyle.FixedDialog;MinimizeBox=false;MaximizeBox=false;ClientSize=new Size(610,190);var p=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(14),ColumnCount=2,RowCount=5};p.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));p.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));var warn=new PictureBox{Image=SystemIcons.Warning.ToBitmap(),SizeMode=PictureBoxSizeMode.AutoSize,Margin=new Padding(0,2,12,0)};p.Controls.Add(warn,0,0);p.SetRowSpan(warn,2);p.Controls.Add(new Label{Text=$"Delete mailbox '{name}'?",AutoSize=true},1,0);p.Controls.Add(new Label{Text="This action cannot be undone.",AutoSize=true,ForeColor=Color.Firebrick},1,1);var apiRow=new TableLayoutPanel{Dock=DockStyle.Top,ColumnCount=2,AutoSize=true,Margin=new Padding(0,8,0,0)};apiRow.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));apiRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));apiRow.Controls.Add(new Label{Text="API key",AutoSize=true,Anchor=AnchorStyles.Left,Margin=new Padding(0,3,10,0)},0,0);input.Dock=DockStyle.Fill;apiRow.Controls.Add(input,1,0);p.Controls.Add(apiRow,1,2);p.Controls.Add(invalid,1,3);var host=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,AutoSize=true};host.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));host.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));host.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));var b=new FlowLayoutPanel{AutoSize=true,WrapContents=false};b.Controls.AddRange([delBtn,cancel]);host.Controls.Add(b,1,0);p.Controls.Add(host,0,4);p.SetColumnSpan(host,2);Controls.Add(p);delBtn.DialogResult=DialogResult.OK;cancel.DialogResult=DialogResult.Cancel;CancelButton=cancel;input.TextChanged+=(_,_)=>ValidateKey();}void ValidateKey(){if(input.TextLength==0){invalid.Text="";delBtn.Enabled=false;input.BackColor=SystemColors.Window;return;}bool ok=FixedEquals(actual,input.Text);invalid.Text=ok?"":"Invalid API key.";delBtn.Enabled=ok;input.BackColor=ok?SystemColors.Window:Color.MistyRose;}}
}