using System.Text.Json;
using System.Text.RegularExpressions;

namespace VPBridgeTray;

internal sealed class SUBLogForm:Form
{
 readonly string logPath,statusPath,configPath;
 readonly CheckedListBox filters=new(){Dock=DockStyle.Fill,CheckOnClick=true};
 readonly DataGridView grid=new(){Dock=DockStyle.Fill,ReadOnly=true,AllowUserToAddRows=false,AllowUserToDeleteRows=false,AllowUserToResizeRows=false,RowHeadersVisible=false,SelectionMode=DataGridViewSelectionMode.FullRowSelect,MultiSelect=false,AutoGenerateColumns=false};
 readonly TextBox search=new(){Width=230,PlaceholderText="Search..."};
 readonly Button clearSearch=new(){Text="×",Width=22,Height=23,Margin=new Padding(2,0,0,0),TabStop=false};
 readonly CheckBox tail=new(){Text="Always at end",Checked=true,AutoSize=true};
 readonly Label serverDot=new(){AutoSize=true,Text="●"};
 readonly Label serverText=new(){AutoSize=true,Text="Server: Unknown"};
 readonly Label filterError=new(){AutoSize=true,ForeColor=Color.Firebrick};
 readonly System.Windows.Forms.Timer timer=new(){Interval=750};
 SplitContainer? split; string last="";LogDetailForm? detail;bool refreshingFilters;
 static readonly Regex TransportRx=new(@"^(?<ts>\d{2}\.\d{2}\.\d{4} \d{2}:\d{2}:\d{2}\.\d{3})\s+#(?<id>\d+)\s+(?<from>[A-Za-z0-9_-]+)→(?<to>[A-Za-z0-9_, -]+)\s+(?<status>RECEIVED|SENT|QUEUED|DROPPED|ERROR)(?:\s+(?<msg>.*))?$",RegexOptions.Compiled);
 static readonly Regex SystemRx=new(@"^(?<ts>\d{2}\.\d{2}\.\d{4} \d{2}:\d{2}:\d{2}\.\d{3})\s+SYSTEM\s+(?<msg>.*)$",RegexOptions.Compiled);

 public SUBLogForm(string log,string db,string status,string config,Icon icon){logPath=log;statusPath=status;configPath=config;Text="Socket Universe Bridge - Diagnostics";Icon=icon;Width=1250;Height=720;StartPosition=FormStartPosition.CenterScreen;Font=SystemFonts.MessageBoxFont??new Font("Segoe UI",9f);BuildUi();filters.ItemCheck+=(_,_)=>BeginInvoke((Action)Render);search.TextChanged+=(_,_)=>{clearSearch.Visible=search.TextLength>0;Render();};clearSearch.Click+=(_,_)=>search.Clear();clearSearch.Visible=false;tail.CheckedChanged+=(_,_)=>ApplyTailMode();grid.SelectionChanged+=(_,_)=>{if(detail!=null&&!detail.IsDisposed)UpdateDetail();};grid.CellDoubleClick+=(_,e)=>{if(e.RowIndex>=0)OpenDetail();};Shown+=(_,_)=>BeginInvoke((Action)ApplyInitialSplitterDistance);RefreshFilters();ApplyTailMode();Poll();timer.Tick+=(_,_)=>Poll();timer.Start();FormClosed+=(_,_)=>{timer.Stop();detail?.Close();};}

 void ApplyInitialSplitterDistance(){if(split==null||split.IsDisposed)return;int width=split.ClientSize.Width;if(width<=0)return;const int desiredPanel1Min=100,desiredPanel2Min=300;int splitterWidth=Math.Max(1,split.SplitterWidth);if(width<desiredPanel1Min+desiredPanel2Min+splitterWidth)return;split.Panel1MinSize=desiredPanel1Min;split.Panel2MinSize=desiredPanel2Min;int min=split.Panel1MinSize;int max=width-split.Panel2MinSize-splitterWidth;if(max<min)return;int target=(int)Math.Round(width*0.10);split.SplitterDistance=Math.Clamp(target,min,max);}

 void BuildUi(){
  var root=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=3,ColumnCount=1,Padding=new Padding(8)};root.RowStyles.Add(new RowStyle(SizeType.AutoSize));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));root.RowStyles.Add(new RowStyle(SizeType.AutoSize));
  var top=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,AutoSize=true,Margin=new Padding(0,0,0,0)};top.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));top.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));top.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
  var statusPanel=new FlowLayoutPanel{AutoSize=true,WrapContents=false,Margin=new Padding(0),Padding=new Padding(0,0,0,4)};serverDot.ForeColor=Color.Gray;statusPanel.Controls.Add(serverDot);statusPanel.Controls.Add(serverText);top.Controls.Add(statusPanel,0,0);top.Controls.Add(new Panel{Dock=DockStyle.Fill},1,0);
  var searchPanel=new FlowLayoutPanel{FlowDirection=FlowDirection.LeftToRight,WrapContents=false,AutoSize=true,Margin=new Padding(0),Padding=new Padding(0,0,0,4)};searchPanel.Controls.Add(search);searchPanel.Controls.Add(clearSearch);top.Controls.Add(searchPanel,2,0);root.Controls.Add(top,0,0);
  split=new SplitContainer{Dock=DockStyle.Fill,FixedPanel=FixedPanel.Panel1};
  var left=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=2,Margin=new Padding(0)};left.RowStyles.Add(new RowStyle(SizeType.AutoSize));left.RowStyles.Add(new RowStyle(SizeType.Percent,100));left.Controls.Add(new Label{Text="Message filters",AutoSize=true,Padding=new Padding(0,5,0,5),BackColor=Color.Gainsboro,Dock=DockStyle.Fill},0,0);left.Controls.Add(filters,0,1);split.Panel1.Controls.Add(left);
  ConfigureGrid();split.Panel2.Controls.Add(grid);root.Controls.Add(split,0,1);
  filterError.Visible=false;Controls.Add(filterError);
  var bottom=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,AutoSize=true,Margin=new Padding(0,6,0,0)};bottom.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));bottom.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));bottom.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));bottom.Controls.Add(tail,0,0);
  var buttons=new FlowLayoutPanel{FlowDirection=FlowDirection.LeftToRight,WrapContents=false,AutoSize=true,Margin=new Padding(0)};var clear=new Button{Text="Clear",AutoSize=true};var cancel=new Button{Text="Cancel",AutoSize=true};clear.Click+=(_,_)=>ClearLog();cancel.Click+=(_,_)=>Close();buttons.Controls.Add(clear);buttons.Controls.Add(cancel);bottom.Controls.Add(buttons,2,0);root.Controls.Add(bottom,0,2);Controls.Add(root);
 }

 void ConfigureGrid(){var ui=SystemFonts.MessageBoxFont??new Font("Segoe UI",9f);grid.DefaultCellStyle.Font=new Font("Consolas",9f);grid.ColumnHeadersDefaultCellStyle.Font=ui;grid.ColumnHeadersDefaultCellStyle.BackColor=Color.Gainsboro;grid.ColumnHeadersDefaultCellStyle.ForeColor=SystemColors.ControlText;grid.EnableHeadersVisualStyles=false;var timeStyle=new DataGridViewCellStyle{Format="dd.MM.yyyy HH:mm:ss.fff",Alignment=DataGridViewContentAlignment.MiddleRight};var rightStyle=new DataGridViewCellStyle{Alignment=DataGridViewContentAlignment.MiddleRight};grid.Columns.Add(new DataGridViewTextBoxColumn{Name="Time",HeaderText="Timecode",Width=185,ValueType=typeof(DateTime),DefaultCellStyle=timeStyle,HeaderCell=new DataGridViewColumnHeaderCell{Style=new DataGridViewCellStyle{Alignment=DataGridViewContentAlignment.MiddleRight,BackColor=Color.Gainsboro}}});grid.Columns.Add(new DataGridViewTextBoxColumn{Name="Id",HeaderText="#",Width=55,DefaultCellStyle=rightStyle,HeaderCell=new DataGridViewColumnHeaderCell{Style=new DataGridViewCellStyle{Alignment=DataGridViewContentAlignment.MiddleRight,BackColor=Color.Gainsboro}}});grid.Columns.Add(new DataGridViewTextBoxColumn{Name="From",HeaderText="From",Width=80});grid.Columns.Add(new DataGridViewTextBoxColumn{Name="To",HeaderText="To",Width=80});grid.Columns.Add(new DataGridViewTextBoxColumn{Name="Status",HeaderText="Status",Width=95});grid.Columns.Add(new DataGridViewTextBoxColumn{Name="Message",HeaderText="Message",AutoSizeMode=DataGridViewAutoSizeColumnMode.Fill});grid.CellFormatting+=(_,e)=>{if(e.RowIndex<0)return;var row=grid.Rows[e.RowIndex];string status=Convert.ToString(row.Cells["Status"].Value)??"",from=Convert.ToString(row.Cells["From"].Value)??"";row.DefaultCellStyle.ForeColor=status is "ERROR" or "DROPPED"?Color.Firebrick:from.Equals("SYSTEM",StringComparison.OrdinalIgnoreCase)?Color.DimGray:status=="RECEIVED"?Color.DarkBlue:status=="SENT"?Color.DarkGreen:status=="QUEUED"?Color.DarkOrange:Color.Black;};}

 void Poll(){RefreshServerState();RefreshFilters();try{if(!File.Exists(logPath)){if(last.Length>0){last="";Render();}return;}var s=File.ReadAllText(logPath);if(s==last)return;last=s;Render();}catch(Exception ex){WriteUiDebug("Traffic log read failed",ex);}}
 void RefreshServerState(){try{if(!File.Exists(statusPath)){SetServerState("Unknown",Color.Gray);return;}using var doc=JsonDocument.Parse(File.ReadAllText(statusPath));bool running=doc.RootElement.TryGetProperty("serverRunning",out var p)&&p.GetBoolean();SetServerState(running?"Running":"Stopped",running?Color.ForestGreen:Color.Firebrick);}catch(Exception ex){SetServerState("Error",Color.Firebrick);WriteUiDebug("Status read failed",ex);}}
 void SetServerState(string state,Color color){serverDot.ForeColor=color;serverText.Text=$"Server: {state}";serverText.ForeColor=SystemColors.ControlText;}

 void RefreshFilters(){if(refreshingFilters)return;refreshingFilters=true;try{var checkedSet=filters.CheckedItems.Cast<string>().ToHashSet(StringComparer.OrdinalIgnoreCase);var ids=new List<string>();if(File.Exists(statusPath)){using var doc=JsonDocument.Parse(File.ReadAllText(statusPath));if(doc.RootElement.TryGetProperty("mailboxes",out var m)&&m.ValueKind==JsonValueKind.Array)foreach(var x in m.EnumerateArray())if(x.ValueKind==JsonValueKind.String&&!string.IsNullOrWhiteSpace(x.GetString()))ids.Add(x.GetString()!);}var desired=new[]{"Ping"}.Concat(ids.Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(x=>x,StringComparer.OrdinalIgnoreCase)).ToList();var current=filters.Items.Cast<string>().ToList();if(!current.SequenceEqual(desired,StringComparer.OrdinalIgnoreCase)){filters.Items.Clear();foreach(var x in desired)filters.Items.Add(x,checkedSet.Count==0||checkedSet.Contains(x));}filterError.Text="";}catch(Exception ex){filterError.Text="Mailbox status error";WriteUiDebug("Mailbox filter status read failed",ex);}finally{refreshingFilters=false;}}

 void Render(){if(IsDisposed)return;var selectedKey=SelectedKey();var enabled=filters.CheckedItems.Cast<string>().ToHashSet(StringComparer.OrdinalIgnoreCase);var needle=search.Text.Trim();var parsed=new List<LogRow>();foreach(var line in last.Split(new[]{"\r\n","\n"},StringSplitOptions.RemoveEmptyEntries)){var row=Parse(line);if(row==null)continue;if(needle.Length>0&&line.IndexOf(needle,StringComparison.OrdinalIgnoreCase)<0)continue;if(IsPing(row)&&!enabled.Contains("Ping"))continue;if(!IsPing(row)&&row.From!="SYSTEM"&&enabled.Count>0&&!enabled.Contains(row.From)&&!enabled.Contains(row.To))continue;parsed.Add(row);}if(tail.Checked)parsed.Sort((a,b)=>a.Time.CompareTo(b.Time));grid.Rows.Clear();foreach(var x in parsed){int i=grid.Rows.Add(x.Time,x.Id,x.From,x.To,x.Status,x.Message);grid.Rows[i].Tag=x;}RestoreSelection(selectedKey);if(tail.Checked&&grid.Rows.Count>0)grid.FirstDisplayedScrollingRowIndex=Math.Max(0,grid.Rows.Count-1);}
 static LogRow? Parse(string line){var m=TransportRx.Match(line);if(m.Success&&DateTime.TryParseExact(m.Groups["ts"].Value,"dd.MM.yyyy HH:mm:ss.fff",null,System.Globalization.DateTimeStyles.None,out var t))return new LogRow(t,m.Groups["id"].Value,m.Groups["from"].Value,m.Groups["to"].Value,m.Groups["status"].Value,m.Groups["msg"].Value,line);m=SystemRx.Match(line);if(m.Success&&DateTime.TryParseExact(m.Groups["ts"].Value,"dd.MM.yyyy HH:mm:ss.fff",null,System.Globalization.DateTimeStyles.None,out t))return new LogRow(t,"","SYSTEM","","",m.Groups["msg"].Value,line);return null;}
 static bool IsPing(LogRow r)=>r.Message.IndexOf("ping",StringComparison.OrdinalIgnoreCase)>=0;
 void ApplyTailMode(){var timeColumn=grid.Columns["Time"];if(tail.Checked){foreach(DataGridViewColumn c in grid.Columns)c.SortMode=DataGridViewColumnSortMode.NotSortable;if(timeColumn!=null){timeColumn.HeaderCell.SortGlyphDirection=SortOrder.None;grid.Sort(timeColumn,System.ComponentModel.ListSortDirection.Ascending);}}else{foreach(DataGridViewColumn c in grid.Columns)c.SortMode=DataGridViewColumnSortMode.Automatic;if(timeColumn!=null)grid.Sort(timeColumn,System.ComponentModel.ListSortDirection.Ascending);}Render();}
 string? SelectedKey()=>grid.SelectedRows.Count==0?null:(grid.SelectedRows[0].Tag as LogRow)?.Raw;
 void RestoreSelection(string? key){grid.ClearSelection();if(key==null)return;foreach(DataGridViewRow r in grid.Rows)if((r.Tag as LogRow)?.Raw==key){r.Selected=true;grid.CurrentCell=r.Cells[0];break;}}
 void OpenDetail(){if(detail==null||detail.IsDisposed){detail=new LogDetailForm(Icon??SystemIcons.Application);detail.FormClosed+=(_,_)=>detail=null;detail.Show();}UpdateDetail();}
 void UpdateDetail(){if(grid.SelectedRows.Count==0)return;if(grid.SelectedRows[0].Tag is LogRow row)detail?.UpdateRow(row);}
 void ClearLog(){if(MessageBox.Show("Clear the entire log file and table?","Clear log",MessageBoxButtons.YesNo,MessageBoxIcon.Warning,MessageBoxDefaultButton.Button2)!=DialogResult.Yes)return;try{File.WriteAllText(logPath,"");last="";grid.Rows.Clear();detail?.ClearRow();}catch(Exception ex){MessageBox.Show("Could not clear the log:\r\n"+ex.Message,"Clear log",MessageBoxButtons.OK,MessageBoxIcon.Error);WriteUiDebug("Clear log failed",ex);}}
 void WriteUiDebug(string message,Exception ex){try{var cfg=BridgeConfig.Load(configPath);if(cfg.logging.debugMode=="OFF")return;var path=Path.Combine(Path.GetDirectoryName(logPath)!,"debug.log");File.AppendAllText(path,$"{DateTime.Now:dd.MM.yyyy HH:mm:ss.fff}  UI DEBUG  {message} | {ex}\r\n");}catch{}}
 internal sealed record LogRow(DateTime Time,string Id,string From,string To,string Status,string Message,string Raw);
}

internal sealed class LogDetailForm:Form
{
 readonly FlowLayoutPanel meta=new(){Dock=DockStyle.Top,Height=38,Padding=new Padding(8,8,8,4),WrapContents=false,AutoScroll=false};readonly RichTextBox body=new(){Dock=DockStyle.Fill,ReadOnly=true,Font=new Font("Consolas",10f),WordWrap=false,ScrollBars=RichTextBoxScrollBars.Both};readonly Label timeValue=new(){AutoSize=true},idValue=new(){AutoSize=true},fromValue=new(){AutoSize=true},toValue=new(){AutoSize=true},statusValue=new(){AutoSize=true};
 public LogDetailForm(Icon icon){Text="Message detail";Icon=icon;Width=780;Height=350;StartPosition=FormStartPosition.CenterScreen;Font=SystemFonts.MessageBoxFont??new Font("Segoe UI",9f);AddMeta("Time:",timeValue);AddMeta("#:",idValue);AddMeta("From:",fromValue);AddMeta("To:",toValue);AddMeta("Status:",statusValue);var bottom=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=42,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(6)};var close=new Button{Text="Close",AutoSize=true};close.Click+=(_,_)=>Close();bottom.Controls.Add(close);Controls.Add(body);Controls.Add(meta);Controls.Add(bottom);}
 void AddMeta(string caption,Label value){var label=new Label{Text=caption,AutoSize=true,Font=new Font(SystemFonts.MessageBoxFont??new Font("Segoe UI",9f),FontStyle.Bold),Margin=new Padding(0,2,3,0)};value.Margin=new Padding(0,2,18,0);meta.Controls.Add(label);meta.Controls.Add(value);}
 public void UpdateRow(SUBLogForm.LogRow r){timeValue.Text=$"{r.Time:dd.MM.yyyy HH:mm:ss.fff}";idValue.Text=r.Id;fromValue.Text=r.From;toValue.Text=r.To;statusValue.Text=r.Status;string text=r.Message;try{using var doc=JsonDocument.Parse(text);text=JsonSerializer.Serialize(doc.RootElement,new JsonSerializerOptions{WriteIndented=true});}catch{}body.Text=text;ColorizeJson();}
 public void ClearRow(){timeValue.Text=idValue.Text=fromValue.Text=toValue.Text=statusValue.Text="";body.Clear();}
 void ColorizeJson(){body.SelectAll();body.SelectionColor=Color.Black;foreach(Match m in Regex.Matches(body.Text,"\"(?:\\.|[^\"])*\"(?=\\s*:)",RegexOptions.Multiline)){body.Select(m.Index,m.Length);body.SelectionColor=Color.DarkRed;}foreach(Match m in Regex.Matches(body.Text,"\"(?:\\.|[^\"])*\"",RegexOptions.Multiline)){body.Select(m.Index,m.Length);if(body.SelectionColor==Color.Black)body.SelectionColor=Color.DarkGreen;}foreach(Match m in Regex.Matches(body.Text,@"\b(true|false|null|-?\d+(?:\.\d+)?)\b")){body.Select(m.Index,m.Length);body.SelectionColor=Color.DarkBlue;}body.Select(0,0);}
}
