using Microsoft.Data.Sqlite;
using System.Reflection;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace VPBridgeTray;

internal sealed class SUBLogForm:Form
{
 const string SeparatorTag="separator";
 readonly string logPath,dbPath,statusPath,configPath;
 readonly ListView filters=new(){Dock=DockStyle.Fill,CheckBoxes=true,View=View.Details,HeaderStyle=ColumnHeaderStyle.None,FullRowSelect=false,MultiSelect=false,HideSelection=false,Margin=new Padding(0),ShowItemToolTips=true};
 readonly DataGridView grid=new(){Dock=DockStyle.Fill,ReadOnly=true,AllowUserToAddRows=false,AllowUserToDeleteRows=false,AllowUserToResizeRows=false,RowHeadersVisible=false,SelectionMode=DataGridViewSelectionMode.FullRowSelect,MultiSelect=false,AutoGenerateColumns=false,ShowCellToolTips=true};
 readonly TextBox search=new(){Width=230,PlaceholderText="Search..."};
 readonly Button clearSearch=new(){Text="×",Width=22,Height=23,Margin=new Padding(2,0,0,0),TabStop=false,Enabled=false};
 readonly CheckBox tail=new(){Text="Always at end",Checked=true,AutoSize=true};
 readonly Label serverDot=new(){AutoSize=true,Text="●"};
 readonly Label serverText=new(){AutoSize=true,Text="Server: Unknown"};
 readonly Label filterError=new(){AutoSize=true,ForeColor=Color.Firebrick};
 readonly System.Windows.Forms.Timer timer=new(){Interval=750};
 readonly Dictionary<string,Color> filterStates=new(StringComparer.OrdinalIgnoreCase);
 readonly Dictionary<string,Color> shownFilterStates=new(StringComparer.OrdinalIgnoreCase);
 readonly Dictionary<string,string> serviceNames=new(StringComparer.OrdinalIgnoreCase);
 readonly Font statusDotFont,pingFont;
 SplitContainer? split;FlowLayoutPanel? tailHost;string last="";LogDetailForm? detail;bool refreshingFilters,filtersInitialized;
 static readonly Regex TransportRx=new(@"^(?<ts>\d{2}\.\d{2}\.\d{4} \d{2}:\d{2}:\d{2}\.\d{3})\s+#(?<id>\d+)\s+(?<from>[A-Za-z0-9_-]+)→(?<to>[A-Za-z0-9_, -]+)\s+(?<status>RECEIVED|SENT|QUEUED|DROPPED|ERROR)(?:\s+(?<msg>.*))?$",RegexOptions.Compiled);
 static readonly Regex SystemRx=new(@"^(?<ts>\d{2}\.\d{2}\.\d{4} \d{2}:\d{2}:\d{2}\.\d{3})\s+SYSTEM\s+(?<msg>.*)$",RegexOptions.Compiled);

 public SUBLogForm(string log,string db,string status,string config,Icon icon){logPath=log;dbPath=db;statusPath=status;configPath=config;Text="Traffic log";Icon=icon;Width=1250;Height=720;StartPosition=FormStartPosition.CenterScreen;Font=SystemFonts.MessageBoxFont??new Font("Segoe UI",9f);statusDotFont=new Font(Font.FontFamily,10f,FontStyle.Bold);pingFont=new Font(Font,FontStyle.Bold);serverDot.Font=new Font(Font.FontFamily,13f,FontStyle.Bold);BuildUi();EnableDoubleBuffering(filters);filters.ItemChecked+=(_,e)=>{if(refreshingFilters||e.Item==null||IsSeparator(e.Item))return;BeginInvoke((Action)Render);};filters.ItemSelectionChanged+=(_,e)=>{if(e.IsSelected&&e.Item!=null&&IsSeparator(e.Item))e.Item.Selected=false;};filters.Resize+=(_,_)=>ResizeFilterColumns();search.TextChanged+=(_,_)=>{clearSearch.Enabled=search.TextLength>0;Render();};clearSearch.Click+=(_,_)=>search.Clear();tail.CheckedChanged+=(_,_)=>ApplyTailMode();grid.SelectionChanged+=(_,_)=>{if(detail!=null&&!detail.IsDisposed)UpdateDetail();};grid.CellDoubleClick+=(_,e)=>{if(e.RowIndex>=0)OpenDetail();};grid.CellToolTipTextNeeded+=GridToolTip;Shown+=(_,_)=>BeginInvoke((Action)(()=>{ApplyInitialSplitterDistance();ResizeFilterColumns();AlignBottomControls();}));RefreshServiceNames();RefreshFilters();ApplyTailMode();Poll();timer.Tick+=(_,_)=>Poll();timer.Start();FormClosed+=(_,_)=>{timer.Stop();detail?.Close();statusDotFont.Dispose();pingFont.Dispose();};}

 void BuildUi(){
  var root=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=3,ColumnCount=1,Padding=new Padding(8)};root.RowStyles.Add(new RowStyle(SizeType.Absolute,30));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));root.RowStyles.Add(new RowStyle(SizeType.AutoSize));
  var top=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,Margin=new Padding(0)};top.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));top.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));top.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
  var statusPanel=new TableLayoutPanel{AutoSize=true,ColumnCount=2,RowCount=1,Margin=new Padding(0),Anchor=AnchorStyles.Left};statusPanel.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));statusPanel.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));serverDot.ForeColor=Color.Gray;serverDot.Anchor=AnchorStyles.None;serverDot.Margin=new Padding(0,0,4,0);serverText.Anchor=AnchorStyles.None;statusPanel.Controls.Add(serverDot,0,0);statusPanel.Controls.Add(serverText,1,0);top.Controls.Add(statusPanel,0,0);top.Controls.Add(new Panel{Dock=DockStyle.Fill},1,0);
  var searchPanel=new TableLayoutPanel{AutoSize=true,ColumnCount=2,RowCount=1,Margin=new Padding(0),Anchor=AnchorStyles.Right};searchPanel.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));searchPanel.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));search.Anchor=AnchorStyles.None;clearSearch.Anchor=AnchorStyles.None;searchPanel.Controls.Add(search,0,0);searchPanel.Controls.Add(clearSearch,1,0);top.Controls.Add(searchPanel,2,0);root.Controls.Add(top,0,0);
  split=new SplitContainer{Dock=DockStyle.Fill,FixedPanel=FixedPanel.Panel1};split.SplitterMoved+=(_,_)=>AlignBottomControls();
  var left=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=3,ColumnCount=1,Margin=new Padding(0)};left.RowStyles.Add(new RowStyle(SizeType.AutoSize));left.RowStyles.Add(new RowStyle(SizeType.Percent,100));left.RowStyles.Add(new RowStyle(SizeType.AutoSize));
  left.Controls.Add(new Label{Text="Message filters",AutoSize=true,Padding=new Padding(0,5,0,5),Margin=new Padding(0),BackColor=Color.Gainsboro,Dock=DockStyle.Fill},0,0);
  filters.Columns.Add("Service name",90,HorizontalAlignment.Left);filters.Columns.Add("Status",24,HorizontalAlignment.Center);left.Controls.Add(filters,0,1);filterError.Visible=false;left.Controls.Add(filterError,0,2);split.Panel1.Controls.Add(left);
  ConfigureGrid();split.Panel2.Controls.Add(grid);root.Controls.Add(split,0,1);
  var bottom=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,AutoSize=true,Margin=new Padding(0,6,0,0)};bottom.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));bottom.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));tailHost=new FlowLayoutPanel{Dock=DockStyle.Fill,AutoSize=true,WrapContents=false,Margin=new Padding(0)};tailHost.Controls.Add(tail);bottom.Controls.Add(tailHost,0,0);var buttons=new FlowLayoutPanel{FlowDirection=FlowDirection.LeftToRight,WrapContents=false,AutoSize=true,Margin=new Padding(0)};var clear=new Button{Text="Clear",AutoSize=true};var cancel=new Button{Text="Cancel",AutoSize=true};clear.Click+=(_,_)=>ClearLog();cancel.Click+=(_,_)=>Close();buttons.Controls.Add(clear);buttons.Controls.Add(cancel);bottom.Controls.Add(buttons,1,0);root.Controls.Add(bottom,0,2);Controls.Add(root);
 }

 static bool IsSeparator(ListViewItem item)=>item.Tag as string==SeparatorTag;
 static void EnableDoubleBuffering(Control c){try{typeof(Control).GetProperty("DoubleBuffered",BindingFlags.Instance|BindingFlags.NonPublic)?.SetValue(c,true);}catch{}}
 void ApplyInitialSplitterDistance(){if(split==null||split.IsDisposed)return;int width=split.ClientSize.Width;if(width<=0)return;const int p1=120,p2=300;int sw=Math.Max(1,split.SplitterWidth);if(width<p1+p2+sw)return;split.Panel1MinSize=p1;split.Panel2MinSize=p2;split.SplitterDistance=Math.Clamp((int)Math.Round(width*.18),p1,width-p2-sw);AlignBottomControls();}
 void AlignBottomControls(){if(split==null||tailHost==null)return;tailHost.Padding=new Padding(split.SplitterDistance+split.SplitterWidth,0,0,0);}
 void ResizeFilterColumns(){if(filters.Columns.Count<2)return;filters.Columns[1].Width=24;filters.Columns[0].Width=Math.Max(45,filters.ClientSize.Width-filters.Columns[1].Width-4);foreach(ListViewItem item in filters.Items)if(IsSeparator(item))item.Text=SeparatorText();}
 string SeparatorText(){int chars=Math.Max(8,(filters.Columns.Count>0?filters.Columns[0].Width:90)/7);return new string('─',chars);}
 string FilterToolTip(string service)=>service.Equals("Ping",StringComparison.OrdinalIgnoreCase)?"Ping traffic":NameFor(service);

 void ConfigureGrid(){var ui=SystemFonts.MessageBoxFont??new Font("Segoe UI",9f);grid.DefaultCellStyle.Font=new Font("Consolas",9f);grid.ColumnHeadersDefaultCellStyle.Font=ui;grid.ColumnHeadersDefaultCellStyle.BackColor=Color.Gainsboro;grid.ColumnHeadersDefaultCellStyle.ForeColor=SystemColors.ControlText;grid.ColumnHeadersDefaultCellStyle.Alignment=DataGridViewContentAlignment.MiddleLeft;grid.EnableHeadersVisualStyles=false;var timeStyle=new DataGridViewCellStyle{Format="dd.MM.yyyy HH:mm:ss.fff",Alignment=DataGridViewContentAlignment.MiddleRight};var rightStyle=new DataGridViewCellStyle{Alignment=DataGridViewContentAlignment.MiddleRight};grid.Columns.Add(new DataGridViewTextBoxColumn{Name="Time",HeaderText="Timecode",Width=185,ValueType=typeof(DateTime),DefaultCellStyle=timeStyle});grid.Columns.Add(new DataGridViewTextBoxColumn{Name="Id",HeaderText="#",Width=55,DefaultCellStyle=rightStyle});grid.Columns.Add(new DataGridViewTextBoxColumn{Name="From",HeaderText="From",Width=90});grid.Columns.Add(new DataGridViewTextBoxColumn{Name="To",HeaderText="To",Width=90});grid.Columns.Add(new DataGridViewTextBoxColumn{Name="Status",HeaderText="Status",Width=95});grid.Columns.Add(new DataGridViewTextBoxColumn{Name="Message",HeaderText="Message",AutoSizeMode=DataGridViewAutoSizeColumnMode.Fill});grid.CellFormatting+=(_,e)=>{if(e.RowIndex<0)return;var row=grid.Rows[e.RowIndex];string status=Convert.ToString(row.Cells["Status"].Value)??"",from=Convert.ToString(row.Cells["From"].Value)??"";row.DefaultCellStyle.ForeColor=status is "ERROR" or "DROPPED"?Color.Firebrick:from.Equals("SYSTEM",StringComparison.OrdinalIgnoreCase)?Color.DimGray:status=="RECEIVED"?Color.DarkBlue:status=="SENT"?Color.DarkGreen:status=="QUEUED"?Color.DarkOrange:Color.Black;};}
 void GridToolTip(object? s,DataGridViewCellToolTipTextNeededEventArgs e){if(e.RowIndex<0||e.ColumnIndex<0)return;string col=grid.Columns[e.ColumnIndex].Name;if(col is not("From" or "To"))return;string service=Convert.ToString(grid.Rows[e.RowIndex].Cells[e.ColumnIndex].Value)??"";e.ToolTipText=NameFor(service);}
 void Poll(){RefreshServerState();RefreshServiceNames();RefreshFilters();try{if(!File.Exists(logPath)){if(last.Length>0){last="";Render();}return;}var s=File.ReadAllText(logPath);if(s==last)return;last=s;Render();}catch(Exception ex){WriteUiDebug("Traffic log read failed",ex);}}
 void RefreshServerState(){try{if(!File.Exists(statusPath)){SetServerState("Unknown",Color.Gray);return;}using var doc=JsonDocument.Parse(File.ReadAllText(statusPath));bool running=doc.RootElement.TryGetProperty("serverRunning",out var p)&&p.GetBoolean();SetServerState(running?"Running":"Stopped",running?Color.ForestGreen:Color.Firebrick);}catch(Exception ex){SetServerState("Error",Color.Firebrick);WriteUiDebug("Status read failed",ex);}}
 void SetServerState(string state,Color color){if(serverDot.ForeColor!=color)serverDot.ForeColor=color;string text=$"Server: {state}";if(serverText.Text!=text)serverText.Text=text;serverText.ForeColor=SystemColors.ControlText;}
 void RefreshServiceNames(){try{var next=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);if(File.Exists(dbPath)){using var c=new SqliteConnection($"Data Source={dbPath};Mode=ReadOnly");c.Open();using var q=c.CreateCommand();q.CommandText="SELECT id,friendly_name FROM mailboxes";using var r=q.ExecuteReader();while(r.Read())next[r.GetString(0)]=r.GetString(1);}if(serviceNames.Count!=next.Count||serviceNames.Any(x=>!next.TryGetValue(x.Key,out var v)||v!=x.Value)){serviceNames.Clear();foreach(var x in next)serviceNames[x.Key]=x.Value;foreach(ListViewItem item in filters.Items)if(!IsSeparator(item))item.ToolTipText=FilterToolTip(item.Text);}}catch{}}
 string NameFor(string service){if(string.IsNullOrWhiteSpace(service))return "";var parts=service.Split(',',StringSplitOptions.TrimEntries|StringSplitOptions.RemoveEmptyEntries);if(parts.Length==0)return service;if(parts.Length==1&&serviceNames.TryGetValue(parts[0],out var one))return one;return string.Join(", ",parts.Select(x=>serviceNames.TryGetValue(x,out var n)?n:x));}

 void RefreshFilters(){if(refreshingFilters)return;refreshingFilters=true;try{var checkedSet=filters.CheckedItems.Cast<ListViewItem>().Where(x=>!IsSeparator(x)).Select(x=>x.Text).ToHashSet(StringComparer.OrdinalIgnoreCase);var ids=new List<string>();filterStates.Clear();if(File.Exists(statusPath)){using var doc=JsonDocument.Parse(File.ReadAllText(statusPath));var root=doc.RootElement;bool serverRunning=root.TryGetProperty("serverRunning",out var sr)&&sr.GetBoolean();filterStates["Ping"]=serverRunning?Color.ForestGreen:Color.Firebrick;if(root.TryGetProperty("mailboxes",out var m)&&m.ValueKind==JsonValueKind.Array)foreach(var x in m.EnumerateArray())if(x.ValueKind==JsonValueKind.String&&!string.IsNullOrWhiteSpace(x.GetString()))ids.Add(x.GetString()!);if(root.TryGetProperty("connections",out var connections)&&connections.ValueKind==JsonValueKind.Object)foreach(var p in connections.EnumerateObject())filterStates[p.Name]=p.Value.ValueKind==JsonValueKind.True?Color.ForestGreen:p.Value.ValueKind==JsonValueKind.False?Color.Firebrick:Color.Gray;if(root.TryGetProperty("vpConnected",out var vp)&&!filterStates.ContainsKey("vp"))filterStates["vp"]=vp.GetBoolean()?Color.ForestGreen:Color.Firebrick;if(root.TryGetProperty("bcConnected",out var bc)&&!filterStates.ContainsKey("bc"))filterStates["bc"]=bc.GetBoolean()?Color.ForestGreen:Color.Firebrick;}else filterStates["Ping"]=Color.Gray;foreach(var id in ids)if(!filterStates.ContainsKey(id))filterStates[id]=Color.Gray;
   var desired=new[]{"Ping"}.Concat(ids.Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(x=>x,StringComparer.OrdinalIgnoreCase)).ToList();var current=filters.Items.Cast<ListViewItem>().Where(x=>!IsSeparator(x)).Select(x=>x.Text).ToList();if(!current.SequenceEqual(desired,StringComparer.OrdinalIgnoreCase)){filters.BeginUpdate();filters.Items.Clear();shownFilterStates.Clear();foreach(var x in desired){var item=new ListViewItem(x){ToolTipText=FilterToolTip(x)};item.SubItems.Add("●");item.Checked=!filtersInitialized||checkedSet.Contains(x);item.UseItemStyleForSubItems=false;item.SubItems[1].Font=statusDotFont;if(x.Equals("Ping",StringComparison.OrdinalIgnoreCase))item.Font=pingFont;filters.Items.Add(item);if(x.Equals("Ping",StringComparison.OrdinalIgnoreCase)){var sep=new ListViewItem(SeparatorText()){Tag=SeparatorTag,ForeColor=SystemColors.ControlDark,UseItemStyleForSubItems=true};sep.SubItems.Add("");sep.StateImageIndex=-1;filters.Items.Add(sep);}}filters.EndUpdate();filtersInitialized=true;ResizeFilterColumns();}
   foreach(ListViewItem item in filters.Items){if(IsSeparator(item)){if(item.Checked)item.Checked=false;item.StateImageIndex=-1;continue;}var next=filterStates.TryGetValue(item.Text,out var c)?c:Color.Gray;if(shownFilterStates.TryGetValue(item.Text,out var old)&&old==next)continue;shownFilterStates[item.Text]=next;item.UseItemStyleForSubItems=false;while(item.SubItems.Count<2)item.SubItems.Add("●");item.SubItems[1].Text="●";item.SubItems[1].ForeColor=next;item.SubItems[1].Font=statusDotFont;filters.Invalidate(item.Bounds);}filterError.Text="";}catch(Exception ex){filterError.Text="Socket Box status error";WriteUiDebug("Socket Box filter status read failed",ex);}finally{refreshingFilters=false;}}
 void Render(){if(IsDisposed)return;var selectedKey=SelectedKey();var topKey=FirstDisplayedKey();string? sortColumn=!tail.Checked?grid.SortedColumn?.Name:null;var sortDirection=grid.SortOrder==SortOrder.Descending?System.ComponentModel.ListSortDirection.Descending:System.ComponentModel.ListSortDirection.Ascending;var enabled=filters.CheckedItems.Cast<ListViewItem>().Where(x=>!IsSeparator(x)).Select(x=>x.Text).ToHashSet(StringComparer.OrdinalIgnoreCase);var needle=search.Text.Trim();var parsed=new List<LogRow>();foreach(var line in last.Split(new[]{"\r\n","\n"},StringSplitOptions.RemoveEmptyEntries)){var row=Parse(line);if(row==null)continue;if(needle.Length>0&&line.IndexOf(needle,StringComparison.OrdinalIgnoreCase)<0)continue;if(IsPing(row)){if(!enabled.Contains("Ping"))continue;}else if(row.From!="SYSTEM"&&!enabled.Contains(row.From)&&!enabled.Contains(row.To))continue;parsed.Add(row);}if(tail.Checked)parsed.Sort((a,b)=>a.Time.CompareTo(b.Time));grid.Rows.Clear();foreach(var x in parsed){int i=grid.Rows.Add(x.Time,x.Id,x.From,x.To,x.Status,x.Message);grid.Rows[i].Tag=x;}if(!tail.Checked){var col=grid.Columns[sortColumn??"Time"];if(col!=null)grid.Sort(col,sortDirection);RestoreSelection(selectedKey);RestoreFirstDisplayed(topKey);}else SelectTailRow();}
 static LogRow? Parse(string line){var m=TransportRx.Match(line);if(m.Success&&DateTime.TryParseExact(m.Groups["ts"].Value,"dd.MM.yyyy HH:mm:ss.fff",null,System.Globalization.DateTimeStyles.None,out var t))return new LogRow(t,m.Groups["id"].Value,m.Groups["from"].Value,m.Groups["to"].Value,m.Groups["status"].Value,m.Groups["msg"].Value,line);m=SystemRx.Match(line);if(m.Success&&DateTime.TryParseExact(m.Groups["ts"].Value,"dd.MM.yyyy HH:mm:ss.fff",null,System.Globalization.DateTimeStyles.None,out t))return new LogRow(t,"","SYSTEM","","",m.Groups["msg"].Value,line);return null;}
 static bool IsPing(LogRow r)=>r.Message.IndexOf("ping",StringComparison.OrdinalIgnoreCase)>=0;
 void ApplyTailMode(){var selectedKey=SelectedKey();var topKey=FirstDisplayedKey();var timeColumn=grid.Columns["Time"];if(tail.Checked){foreach(DataGridViewColumn c in grid.Columns)c.SortMode=DataGridViewColumnSortMode.NotSortable;if(timeColumn!=null)timeColumn.HeaderCell.SortGlyphDirection=SortOrder.None;}else{foreach(DataGridViewColumn c in grid.Columns)c.SortMode=DataGridViewColumnSortMode.Automatic;}Render();if(!tail.Checked){RestoreSelection(selectedKey);RestoreFirstDisplayed(topKey);}}
 void SelectTailRow(){grid.ClearSelection();if(grid.Rows.Count==0)return;var row=grid.Rows[grid.Rows.Count-1];row.Selected=true;grid.CurrentCell=row.Cells[0];int shown=Math.Max(1,grid.DisplayedRowCount(false));try{grid.FirstDisplayedScrollingRowIndex=Math.Max(0,grid.Rows.Count-shown);}catch{}}
 string? SelectedKey()=>grid.SelectedRows.Count==0?null:(grid.SelectedRows[0].Tag as LogRow)?.Raw;
 string? FirstDisplayedKey(){int i=grid.FirstDisplayedScrollingRowIndex;return i>=0&&i<grid.Rows.Count?(grid.Rows[i].Tag as LogRow)?.Raw:null;}
 void RestoreSelection(string? key){grid.ClearSelection();if(key==null)return;foreach(DataGridViewRow r in grid.Rows)if((r.Tag as LogRow)?.Raw==key){r.Selected=true;grid.CurrentCell=r.Cells[0];break;}}
 void RestoreFirstDisplayed(string? key){if(key==null)return;foreach(DataGridViewRow r in grid.Rows)if((r.Tag as LogRow)?.Raw==key){try{grid.FirstDisplayedScrollingRowIndex=r.Index;}catch{}break;}}
 void OpenDetail(){if(detail==null||detail.IsDisposed){detail=new LogDetailForm(Icon??SystemIcons.Application,NameFor);detail.FormClosed+=(_,_)=>detail=null;detail.Show();}UpdateDetail();}
 void UpdateDetail(){if(grid.SelectedRows.Count==0)return;if(grid.SelectedRows[0].Tag is LogRow row)detail?.UpdateRow(row);}
 void ClearLog(){if(MessageBox.Show("Clear the entire log file and table?","Clear log",MessageBoxButtons.YesNo,MessageBoxIcon.Warning,MessageBoxDefaultButton.Button2)!=DialogResult.Yes)return;try{File.WriteAllText(logPath,"");last="";grid.Rows.Clear();detail?.ClearRow();}catch(Exception ex){MessageBox.Show("Could not clear the log:\r\n"+ex.Message,"Clear log",MessageBoxButtons.OK,MessageBoxIcon.Error);WriteUiDebug("Clear log failed",ex);}}
 void WriteUiDebug(string message,Exception ex){try{var cfg=BridgeConfig.Load(configPath);if(cfg.logging.debugMode.Equals("off",StringComparison.OrdinalIgnoreCase))return;var path=Path.Combine(Path.GetDirectoryName(logPath)!,"debug.log");File.AppendAllText(path,$"{DateTime.Now:dd.MM.yyyy HH:mm:ss.fff}  UI DEBUG  {message} | {ex}\r\n");}catch{}}
 internal sealed record LogRow(DateTime Time,string Id,string From,string To,string Status,string Message,string Raw);
}

internal sealed class LogDetailForm:Form
{
 readonly FlowLayoutPanel meta=new(){Dock=DockStyle.Top,Height=38,Padding=new Padding(8,8,8,4),WrapContents=false,AutoScroll=false};
 readonly TreeView tree=new(){Dock=DockStyle.Fill,Font=new Font("Consolas",10f),HideSelection=false};
 readonly RichTextBox body=new(){Dock=DockStyle.Fill,ReadOnly=true,Font=new Font("Consolas",10f),WordWrap=false,ScrollBars=RichTextBoxScrollBars.Both};
 readonly Label timeValue=new(){AutoSize=true},idValue=new(){AutoSize=true},fromValue=new(){AutoSize=true},toValue=new(){AutoSize=true},statusValue=new(){AutoSize=true};
 readonly ToolTip tips=new();readonly Func<string,string> nameFor;
 public LogDetailForm(Icon icon,Func<string,string> resolver){nameFor=resolver;Text="Message detail";Icon=icon;Width=780;Height=420;StartPosition=FormStartPosition.CenterScreen;Font=SystemFonts.MessageBoxFont??new Font("Segoe UI",9f);AddMeta("Time:",timeValue);AddMeta("#:",idValue);AddMeta("From:",fromValue);AddMeta("To:",toValue);AddMeta("Status:",statusValue);var host=new Panel{Dock=DockStyle.Fill};host.Controls.Add(body);host.Controls.Add(tree);var bottom=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=42,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(6)};var close=new Button{Text="Close",AutoSize=true};close.Click+=(_,_)=>Close();bottom.Controls.Add(close);Controls.Add(host);Controls.Add(meta);Controls.Add(bottom);}
 void AddMeta(string caption,Label value){var label=new Label{Text=caption,AutoSize=true,Font=new Font(SystemFonts.MessageBoxFont??new Font("Segoe UI",9f),FontStyle.Bold),Margin=new Padding(0,2,3,0)};value.Margin=new Padding(0,2,18,0);meta.Controls.Add(label);meta.Controls.Add(value);}
 public void UpdateRow(SUBLogForm.LogRow r){timeValue.Text=$"{r.Time:dd.MM.yyyy HH:mm:ss.fff}";idValue.Text=r.Id;fromValue.Text=r.From;toValue.Text=r.To;statusValue.Text=r.Status;tips.SetToolTip(fromValue,nameFor(r.From));tips.SetToolTip(toValue,nameFor(r.To));tree.Nodes.Clear();try{using var doc=JsonDocument.Parse(r.Message);tree.Visible=true;body.Visible=false;AddJson(tree.Nodes,"JSON",doc.RootElement);tree.ExpandAll();}catch{tree.Visible=false;body.Visible=true;body.Text=r.Message;}}
 static void AddJson(TreeNodeCollection nodes,string name,JsonElement el){switch(el.ValueKind){case JsonValueKind.Object:{var n=nodes.Add(name);foreach(var p in el.EnumerateObject())AddJson(n.Nodes,p.Name,p.Value);break;}case JsonValueKind.Array:{var n=nodes.Add(name+" [ ]");int i=0;foreach(var v in el.EnumerateArray())AddJson(n.Nodes,$"[{i++}]",v);break;}case JsonValueKind.String:nodes.Add($"{name}: \"{el.GetString()}\"");break;default:nodes.Add($"{name}: {el.GetRawText()}");break;}}
 public void ClearRow(){timeValue.Text=idValue.Text=fromValue.Text=toValue.Text=statusValue.Text="";tree.Nodes.Clear();body.Clear();}
}
