using Microsoft.Data.Sqlite;

namespace VPBridgeTray;
internal sealed class SUBLogForm:Form
{
 readonly string logPath,dbPath; readonly CheckedListBox filters=new(){Dock=DockStyle.Fill,CheckOnClick=true}; readonly RichTextBox text=new(){Dock=DockStyle.Fill,ReadOnly=true,WordWrap=false}; readonly TextBox search=new(){Dock=DockStyle.Fill,PlaceholderText="Search..."}; readonly CheckBox tail=new(){Text="Always at end",Checked=true,AutoSize=true}; readonly System.Windows.Forms.Timer timer=new(){Interval=750}; string last="";
 public SUBLogForm(string log,string db,Icon icon){logPath=log;dbPath=db;Text="Socket Universe Bridge - Diagnostics";Icon=icon;Width=1100;Height=650;StartPosition=FormStartPosition.CenterScreen;var root=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=2};root.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,220));root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));root.RowStyles.Add(new RowStyle(SizeType.AutoSize));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));var top=new FlowLayoutPanel{Dock=DockStyle.Fill,AutoSize=true};top.Controls.Add(tail);var clear=new Button{Text="×",AutoSize=true,Enabled=false};clear.Click+=(_,_)=>search.Clear();top.Controls.Add(search);top.Controls.Add(clear);root.Controls.Add(new Label{Text="Message filters",AutoSize=true,Padding=new Padding(6)},0,0);root.Controls.Add(top,1,0);root.Controls.Add(filters,0,1);root.Controls.Add(text,1,1);Controls.Add(root);LoadFilters();filters.ItemCheck+=(_,_)=>BeginInvoke(Render);search.TextChanged+=(_,_)=>{clear.Enabled=search.TextLength>0;Render();};tail.CheckedChanged+=(_,_)=>{if(tail.Checked){text.SelectionStart=text.TextLength;text.ScrollToCaret();}};timer.Tick+=(_,_)=>Poll();Shown+=(_,_)=>{Poll();timer.Start();};FormClosed+=(_,_)=>timer.Stop();}
 void LoadFilters(){filters.Items.Clear();filters.Items.Add("Ping",true);try{using var c=new SqliteConnection($"Data Source={dbPath}");c.Open();using var q=c.CreateCommand();q.CommandText="SELECT id FROM mailboxes ORDER BY id COLLATE NOCASE";using var r=q.ExecuteReader();while(r.Read())filters.Items.Add(r.GetString(0),true);}catch{}}
 void Poll(){try{if(!File.Exists(logPath))return;var s=File.ReadAllText(logPath);if(s==last)return;last=s;Render();}catch{}}
 void Render(){if(IsDisposed)return;var enabled=filters.CheckedItems.Cast<string>().ToHashSet(StringComparer.OrdinalIgnoreCase);var needle=search.Text.Trim();var lines=last.Split(new[]{"\r\n","\n"},StringSplitOptions.None);var shown=lines.Where(line=>{if(needle.Length>0&&line.IndexOf(needle,StringComparison.OrdinalIgnoreCase)<0)return false;if(line.IndexOf("ping",StringComparison.OrdinalIgnoreCase)>=0)return enabled.Contains("Ping");var mailboxMentioned=false;foreach(var item in filters.Items.Cast<string>().Where(x=>!x.Equals("Ping",StringComparison.OrdinalIgnoreCase))){if(line.IndexOf(item,StringComparison.OrdinalIgnoreCase)>=0){mailboxMentioned=true;if(enabled.Contains(item))return true;}}return !mailboxMentioned;});int pos=text.SelectionStart;int first=text.GetCharIndexFromPosition(new Point(1,1));text.Text=String.Join(Environment.NewLine,shown);if(tail.Checked){text.SelectionStart=text.TextLength;text.ScrollToCaret();}else{text.SelectionStart=Math.Min(pos,text.TextLength);if(first>0){text.SelectionStart=Math.Min(first,text.TextLength);text.ScrollToCaret();text.SelectionStart=Math.Min(pos,text.TextLength);}}}
}
