namespace VPBridgeTray;
internal sealed class SUBSettingsForm:Form
{
 readonly string file;readonly Action saved;readonly ComboBox mode=new(){DropDownStyle=ComboBoxStyle.DropDownList};readonly ComboBox debugMode=new(){DropDownStyle=ComboBoxStyle.DropDownList};readonly NumericUpDown port=new(){Minimum=1,Maximum=65535};readonly NumericUpDown retention=new(){Minimum=1,Maximum=10080};readonly CheckBox startup=new(){Text="",AutoSize=true,Anchor=AnchorStyles.Left};readonly ToolTip tips=new();
 public SUBSettingsForm(string configFile,Action onSaved,Icon icon){file=configFile;saved=onSaved;Text="Socket Universe Bridge - Settings";Icon=icon;StartPosition=FormStartPosition.CenterScreen;AutoSize=true;AutoSizeMode=AutoSizeMode.GrowAndShrink;mode.Items.AddRange(["Local only","All interfaces"]);debugMode.Items.AddRange(["Off","Single","All"]);var cfg=BridgeConfig.Load(file);mode.SelectedIndex=cfg.server.mode=="all"?1:0;port.Value=cfg.server.port;retention.Value=cfg.logging.retentionMinutes;debugMode.SelectedIndex=cfg.logging.debugMode.Equals("single",StringComparison.OrdinalIgnoreCase)?1:cfg.logging.debugMode.Equals("all",StringComparison.OrdinalIgnoreCase)?2:0;startup.Checked=IsStartup();tips.SetToolTip(debugMode,"Off = disabled; Single = current run only; All = append history.");var p=new TableLayoutPanel{AutoSize=true,AutoSizeMode=AutoSizeMode.GrowAndShrink,Padding=new Padding(12),ColumnCount=2,RowCount=0,Margin=new Padding(0)};p.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));p.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,245));Add(p,"Network access",mode);Add(p,"Port",port);AddRetention(p);Add(p,"Debug server",debugMode);Add(p,"Start with Windows",startup);var buttons=new FlowLayoutPanel{FlowDirection=FlowDirection.RightToLeft,AutoSize=true,WrapContents=false,Dock=DockStyle.Fill,Margin=new Padding(0,8,0,0)};var save=new Button{Text="Save",AutoSize=true};var cancel=new Button{Text="Cancel",AutoSize=true};save.Click+=(_,_)=>Save();cancel.Click+=(_,_)=>Close();buttons.Controls.Add(save);buttons.Controls.Add(cancel);int r=p.RowCount++;p.RowStyles.Add(new RowStyle(SizeType.AutoSize));p.Controls.Add(buttons,1,r);Controls.Add(p);}
 static Label RowLabel(string text)=>new(){Text=text,AutoSize=true,Anchor=AnchorStyles.Left,Margin=new Padding(0,0,12,3)};
 static void Add(TableLayoutPanel p,string l,Control c){int r=p.RowCount++;p.RowStyles.Add(new RowStyle(SizeType.AutoSize));p.Controls.Add(RowLabel(l),0,r);c.Dock=DockStyle.Top;c.Margin=new Padding(0,0,0,3);p.Controls.Add(c,1,r);}
 void AddRetention(TableLayoutPanel p){int r=p.RowCount++;p.RowStyles.Add(new RowStyle(SizeType.AutoSize));p.Controls.Add(RowLabel("Traffic log retention"),0,r);var row=new TableLayoutPanel{Dock=DockStyle.Top,ColumnCount=2,RowCount=1,Margin=new Padding(0,0,0,3),AutoSize=true};row.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));row.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));retention.Dock=DockStyle.Fill;retention.Margin=new Padding(0);row.Controls.Add(retention,0,0);row.Controls.Add(new Label{Text="min",AutoSize=true,Anchor=AnchorStyles.Left,Margin=new Padding(6,0,0,0)},1,0);p.Controls.Add(row,1,r);}
 bool IsStartup(){using var k=Microsoft.Win32.Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run");return k?.GetValue("SocketUniverseBridge")!=null;}
 void Save(){var cfg=BridgeConfig.Load(file);cfg.server.mode=mode.SelectedIndex==1?"all":"local";cfg.server.port=(int)port.Value;cfg.logging.retentionMinutes=(int)retention.Value;cfg.logging.debugMode=debugMode.SelectedIndex==1?"single":debugMode.SelectedIndex==2?"all":"off";cfg.Save(file);using var k=Microsoft.Win32.Registry.CurrentUser.CreateSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run");if(startup.Checked)k.SetValue("SocketUniverseBridge",$"\"{Application.ExecutablePath}\"");else k.DeleteValue("SocketUniverseBridge",false);saved();Close();}
}
