namespace VPBridgeTray;
internal sealed class SUBSettingsForm:Form
{
 readonly string file;readonly Action saved;readonly ComboBox mode=new(){DropDownStyle=ComboBoxStyle.DropDownList};readonly ComboBox debugMode=new(){DropDownStyle=ComboBoxStyle.DropDownList};readonly NumericUpDown port=new(){Minimum=1,Maximum=65535};readonly NumericUpDown retention=new(){Minimum=1,Maximum=10080};readonly CheckBox startup=new(){Text="Start automatically",AutoSize=true};
 public SUBSettingsForm(string configFile,Action onSaved,Icon icon){file=configFile;saved=onSaved;Text="Socket Universe Bridge - Settings";Icon=icon;Width=500;Height=330;StartPosition=FormStartPosition.CenterScreen;mode.Items.AddRange(["Local only","All interfaces"]);debugMode.Items.AddRange(["OFF","SINGLE","ALL"]);var cfg=BridgeConfig.Load(file);mode.SelectedIndex=cfg.server.mode=="all"?1:0;port.Value=cfg.server.port;retention.Value=cfg.logging.retentionMinutes;debugMode.SelectedItem=cfg.logging.debugMode;startup.Checked=IsStartup();var p=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(15),ColumnCount=2};p.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,170));p.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));Add(p,"Listen",mode);Add(p,"Port",port);Add(p,"Log retention [min]",retention);Add(p,"Debug logging",debugMode);p.Controls.Add(new Label{Text="OFF = disabled, SINGLE = current run only, ALL = append history",AutoSize=true,ForeColor=Color.DimGray},1,p.RowCount++);p.Controls.Add(startup,1,p.RowCount++);var buttons=new FlowLayoutPanel{FlowDirection=FlowDirection.RightToLeft,Dock=DockStyle.Fill,AutoSize=true};var save=new Button{Text="Save",AutoSize=true};var cancel=new Button{Text="Cancel",AutoSize=true};save.Click+=(_,_)=>Save();cancel.Click+=(_,_)=>Close();buttons.Controls.Add(save);buttons.Controls.Add(cancel);p.Controls.Add(buttons,1,p.RowCount++);Controls.Add(p);}
 static void Add(TableLayoutPanel p,string l,Control c){int r=p.RowCount++;p.Controls.Add(new Label{Text=l,AutoSize=true,Padding=new Padding(0,6,0,0)},0,r);c.Dock=DockStyle.Top;p.Controls.Add(c,1,r);}
 bool IsStartup(){using var k=Microsoft.Win32.Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run");return k?.GetValue("SocketUniverseBridge")!=null;}
 void Save(){var cfg=BridgeConfig.Load(file);cfg.server.mode=mode.SelectedIndex==1?"all":"local";cfg.server.port=(int)port.Value;cfg.logging.retentionMinutes=(int)retention.Value;cfg.logging.debugMode=debugMode.SelectedItem?.ToString()??"OFF";cfg.Save(file);using var k=Microsoft.Win32.Registry.CurrentUser.CreateSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run");if(startup.Checked)k.SetValue("SocketUniverseBridge",$"\"{Application.ExecutablePath}\"");else k.DeleteValue("SocketUniverseBridge",false);saved();Close();}
}
